'use strict';

function loadContractsDiagnostics() {
  try {
    return require('@pulse-compute/wasm-contracts/diagnostics');
  } catch (error) {
    if (error && error.code === 'MODULE_NOT_FOUND' && String(error.message).includes('@pulse-compute/wasm-contracts')) {
      return require('../../../contracts/src/diagnostics.js');
    }
    throw error;
  }
}

const crypto = require('node:crypto');
const { PACKAGE_VERSION, normalizeArtifact } = loadContractsDiagnostics();

const ASSEMBLYSCRIPT_CORE_VERSION = 'pulsewasm.assemblyscript-core.v3';
const ASSEMBLYSCRIPT_HANDLERS_VERSION = 'pulsewasm.assemblyscript-handlers.v1';

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

function makeFile(file, text) {
  return {
    file,
    bytes: Buffer.byteLength(text, 'utf8'),
    sha256: sha256(text),
    text
  };
}

function asString(value) {
  return JSON.stringify(String(value ?? ''));
}

function safeIdentifier(value, fallback = 'handler') {
  const raw = String(value || fallback).replace(/[^A-Za-z0-9_$]/g, '_');
  const cleaned = raw.length > 0 ? raw : fallback;
  return /^[A-Za-z_$]/.test(cleaned) ? cleaned : `_${cleaned}`;
}

function handlerBaseRole(slot) {
  return String((slot?.roles || [])[0] || '').split(':')[0] || 'unknown';
}

function handlerExternalName(slot) {
  return `__pulsewasm_handler_${Number(slot.slot) | 0}_${safeIdentifier(slot.name || slot.id || 'handler')}`;
}

function handlerExternalField(slot) {
  return String(slot.exportName || slot.name || slot.id || `handler_${slot.slot}`);
}

function sortHandlerSlots(dispatchTable) {
  return (dispatchTable?.handlerSlots || []).slice().sort((a, b) => Number(a.slot) - Number(b.slot));
}

function header(phase = '9C') {
  return [
    '/*',
    ` * Generated by PulseWasm Phase ${phase}.`,
    ' * Do not edit by hand.',
    ' *',
    ' * This AssemblyScript runtime surface is generated from validated PulseWasm artifacts.',
    ' * It must not re-read user source or re-infer route semantics.',
    ' */',
    ''
  ].join('\n');
}

function buildRuntimePathSource() {
  return `${header()}import {
  SEGMENT_LITERAL,
  SEGMENT_PARAM,
  SEGMENT_WILDCARD
} from './types.as'

import {
  EXECUTION_ENTRY_COUNT,
  ENTRY_KINDS,
  ENTRY_SEGMENT_OFFSETS,
  ENTRY_SEGMENT_LENGTHS,
  ENTRY_SEGMENT_KINDS,
  ENTRY_SEGMENT_VALUES
} from './route-table.as'

// Entry kind ABI duplicated here to keep runtime-path self-contained.
export const ENTRY_UNKNOWN: i32 = 0
export const ENTRY_USE: i32 = 1
export const ENTRY_ROUTE: i32 = 2
export const ENTRY_ERROR: i32 = 3
export const ENTRY_CHANNEL: i32 = 4
export const ENTRY_LIFECYCLE: i32 = 5
export const ENTRY_MOUNT: i32 = 6

const SLASH: i32 = 47

export class PulseWasmParamsView {
  entryIndex: i32
  requestPath: string
  count: i32

  constructor() {
    this.entryIndex = -1
    this.requestPath = '/'
    this.count = 0
  }

  reset(entryIndex: i32, requestPath: string): void {
    this.entryIndex = entryIndex
    this.requestPath = normalizeRequestPath(requestPath)
    this.count = entryParamCount(entryIndex)
  }
}

export function resetParamsView(view: PulseWasmParamsView, entryIndex: i32, requestPath: string): void {
  view.reset(entryIndex, requestPath)
}

export function normalizeRequestPath(input: string): string {
  let path = input.length == 0 ? '/' : input
  if (path.charCodeAt(0) != SLASH) path = '/' + path
  while (path.length > 1 && path.charCodeAt(path.length - 1) == SLASH) {
    path = path.substring(0, path.length - 1)
  }
  return path
}

export function requestPathIsValid(input: string): bool {
  const path = normalizeRequestPath(input)
  if (path.length == 0) return false
  if (path.charCodeAt(0) != SLASH) return false
  for (let i: i32 = 1; i < path.length; i++) {
    if (path.charCodeAt(i) == SLASH && path.charCodeAt(i - 1) == SLASH) return false
  }
  return true
}

function hasLeadingSlash(path: string): bool {
  return path.length > 0 && path.charCodeAt(0) == SLASH
}

export function pathSegmentCount(input: string): i32 {
  const path = normalizeRequestPath(input)
  if (!requestPathIsValid(path)) return -1
  let count: i32 = 0
  let start: i32 = hasLeadingSlash(path) ? 1 : 0
  const length: i32 = path.length
  if (length == 1) return 0
  for (let i: i32 = start; i <= length; i++) {
    if (i == length || path.charCodeAt(i) == SLASH) {
      if (i <= start) return -1
      count++
      start = i + 1
    }
  }
  return count
}

export function pathSegmentStartAt(input: string, targetIndex: i32): i32 {
  if (targetIndex < 0) return -1
  const path = normalizeRequestPath(input)
  if (!requestPathIsValid(path)) return -1
  let current: i32 = 0
  let start: i32 = hasLeadingSlash(path) ? 1 : 0
  const length: i32 = path.length
  if (length == 1) return -1
  for (let i: i32 = start; i <= length; i++) {
    if (i == length || path.charCodeAt(i) == SLASH) {
      if (i <= start) return -1
      if (current == targetIndex) return start
      current++
      start = i + 1
    }
  }
  return -1
}

export function pathSegmentEndAt(input: string, targetIndex: i32): i32 {
  if (targetIndex < 0) return -1
  const path = normalizeRequestPath(input)
  if (!requestPathIsValid(path)) return -1
  let current: i32 = 0
  let start: i32 = hasLeadingSlash(path) ? 1 : 0
  const length: i32 = path.length
  if (length == 1) return -1
  for (let i: i32 = start; i <= length; i++) {
    if (i == length || path.charCodeAt(i) == SLASH) {
      if (i <= start) return -1
      if (current == targetIndex) return i
      current++
      start = i + 1
    }
  }
  return -1
}

export function pathSegmentLengthAt(input: string, targetIndex: i32): i32 {
  const start = pathSegmentStartAt(input, targetIndex)
  if (start < 0) return -1
  const end = pathSegmentEndAt(input, targetIndex)
  if (end < start) return -1
  return end - start
}

export function pathSegmentAt(input: string, targetIndex: i32): string {
  const path = normalizeRequestPath(input)
  const start = pathSegmentStartAt(path, targetIndex)
  if (start < 0) return ''
  const end = pathSegmentEndAt(path, targetIndex)
  if (end < start) return ''
  return path.substring(start, end)
}

export function entryPatternSegmentCount(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return 0
  return unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
}

export function entryPatternSegmentKindAt(entryIndex: i32, segmentIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return 0
  const length = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  if (segmentIndex < 0 || segmentIndex >= length) return 0
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  return unchecked(ENTRY_SEGMENT_KINDS[offset + segmentIndex])
}

export function entryPatternSegmentValueAt(entryIndex: i32, segmentIndex: i32): string {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return ''
  const length = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  if (segmentIndex < 0 || segmentIndex >= length) return ''
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  return unchecked(ENTRY_SEGMENT_VALUES[offset + segmentIndex])
}

export function entryHasWildcard(entryIndex: i32): bool {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return false
  const length = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  for (let i: i32 = 0; i < length; i++) {
    if (unchecked(ENTRY_SEGMENT_KINDS[offset + i]) == SEGMENT_WILDCARD) return true
  }
  return false
}

export function entryPathMatches(entryIndex: i32, requestPath: string): bool {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return false
  const path = normalizeRequestPath(requestPath)
  if (!requestPathIsValid(path)) return false

  const patternLength = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  const pathLength = pathSegmentCount(path)
  if (pathLength < 0) return false

  if (patternLength == 0) {
    const kind = unchecked(ENTRY_KINDS[entryIndex])
    // A pathless .use() entry is a global middleware and matches every valid path.
    if (kind == ENTRY_USE) return true
    // Root routes have zero path segments and should only match '/'.
    return pathLength == 0
  }

  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])

  for (let i: i32 = 0; i < patternLength; i++) {
    const kind = unchecked(ENTRY_SEGMENT_KINDS[offset + i])
    if (kind == SEGMENT_WILDCARD) {
      // PulseWasm v1 only emits trailing unnamed wildcards. They match zero or more remaining segments.
      return pathLength >= i
    }
    if (i >= pathLength) return false
    const actualStart = pathSegmentStartAt(path, i)
    const actualEnd = pathSegmentEndAt(path, i)
    if (actualStart < 0 || actualEnd < actualStart) return false
    if (kind == SEGMENT_LITERAL) {
      const expected = unchecked(ENTRY_SEGMENT_VALUES[offset + i])
      if (path.substring(actualStart, actualEnd) != expected) return false
    } else if (kind == SEGMENT_PARAM) {
      if (actualEnd == actualStart) return false
    } else {
      return false
    }
  }

  return pathLength == patternLength
}

export function entryParamCount(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return 0
  const length = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  let count: i32 = 0
  for (let i: i32 = 0; i < length; i++) {
    if (unchecked(ENTRY_SEGMENT_KINDS[offset + i]) == SEGMENT_PARAM) count++
  }
  return count
}

function entryParamSegmentIndexAt(entryIndex: i32, paramIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  if (paramIndex < 0) return -1
  const length = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  let current: i32 = 0
  for (let i: i32 = 0; i < length; i++) {
    if (unchecked(ENTRY_SEGMENT_KINDS[offset + i]) == SEGMENT_PARAM) {
      if (current == paramIndex) return i
      current++
    }
  }
  return -1
}

export function entryParamNameAt(entryIndex: i32, paramIndex: i32): string {
  const segmentIndex = entryParamSegmentIndexAt(entryIndex, paramIndex)
  if (segmentIndex < 0) return ''
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  return unchecked(ENTRY_SEGMENT_VALUES[offset + segmentIndex])
}

export function entryParamValueStartAt(entryIndex: i32, requestPath: string, paramIndex: i32): i32 {
  const segmentIndex = entryParamSegmentIndexAt(entryIndex, paramIndex)
  if (segmentIndex < 0) return -1
  return pathSegmentStartAt(requestPath, segmentIndex)
}

export function entryParamValueLengthAt(entryIndex: i32, requestPath: string, paramIndex: i32): i32 {
  const start = entryParamValueStartAt(entryIndex, requestPath, paramIndex)
  if (start < 0) return -1
  const segmentIndex = entryParamSegmentIndexAt(entryIndex, paramIndex)
  const end = pathSegmentEndAt(requestPath, segmentIndex)
  if (end < start) return -1
  return end - start
}

export function entryParamValueAt(entryIndex: i32, requestPath: string, paramIndex: i32): string {
  const path = normalizeRequestPath(requestPath)
  const start = entryParamValueStartAt(entryIndex, path, paramIndex)
  if (start < 0) return ''
  const length = entryParamValueLengthAt(entryIndex, path, paramIndex)
  if (length < 0) return ''
  return path.substring(start, start + length)
}

export function paramsNameAt(view: PulseWasmParamsView, paramIndex: i32): string {
  return entryParamNameAt(view.entryIndex, paramIndex)
}

export function paramsValueStartAt(view: PulseWasmParamsView, paramIndex: i32): i32 {
  return entryParamValueStartAt(view.entryIndex, view.requestPath, paramIndex)
}

export function paramsValueLengthAt(view: PulseWasmParamsView, paramIndex: i32): i32 {
  return entryParamValueLengthAt(view.entryIndex, view.requestPath, paramIndex)
}

export function paramsValueAt(view: PulseWasmParamsView, paramIndex: i32): string {
  return entryParamValueAt(view.entryIndex, view.requestPath, paramIndex)
}

export function paramsValueByName(view: PulseWasmParamsView, name: string): string {
  for (let i: i32 = 0; i < view.count; i++) {
    if (paramsNameAt(view, i) == name) return paramsValueAt(view, i)
  }
  return ''
}

export function entryWildcardRestStartAt(entryIndex: i32, requestPath: string): i32 {
  if (!entryHasWildcard(entryIndex)) return -1
  const length = unchecked(ENTRY_SEGMENT_LENGTHS[entryIndex])
  const offset = unchecked(ENTRY_SEGMENT_OFFSETS[entryIndex])
  for (let i: i32 = 0; i < length; i++) {
    if (unchecked(ENTRY_SEGMENT_KINDS[offset + i]) == SEGMENT_WILDCARD) {
      if (i >= pathSegmentCount(requestPath)) return normalizeRequestPath(requestPath).length
      return pathSegmentStartAt(requestPath, i)
    }
  }
  return -1
}

export function entryWildcardRestAt(entryIndex: i32, requestPath: string): string {
  const start = entryWildcardRestStartAt(entryIndex, requestPath)
  if (start < 0) return ''
  const path = normalizeRequestPath(requestPath)
  if (start >= path.length) return '/'
  return path.substring(start - 1 >= 0 && path.charCodeAt(start - 1) == SLASH ? start - 1 : start, path.length)
}
`;
}


function buildHandlerSlotsSource(dispatchTable) {
  const slots = sortHandlerSlots(dispatchTable);
  const declarations = [];
  const routeCases = [];
  const middlewareCases = [];
  const lifecycleCases = [];
  const errorCases = [];
  const channelCases = [];

  for (const slot of slots) {
    const role = handlerBaseRole(slot);
    const fn = handlerExternalName(slot);
    const field = handlerExternalField(slot);
    const slotNumber = Number(slot.slot) | 0;

    if (role === 'error') {
      declarations.push(`@external("pulsewasm_handlers", ${asString(field)})\ndeclare function ${fn}(err: usize, ctx: usize, next: usize): void`);
      errorCases.push(`    case ${slotNumber}: ${fn}(err, ctx, next); return true`);
    } else if (role === 'channel') {
      declarations.push(`@external("pulsewasm_handlers", ${asString(field)})\ndeclare function ${fn}(ctx: usize): usize`);
      channelCases.push(`    case ${slotNumber}: return ${fn}(ctx)`);
    } else if (role === 'lifecycle') {
      declarations.push(`@external("pulsewasm_handlers", ${asString(field)})\ndeclare function ${fn}(ctx: usize, next: usize): void`);
      lifecycleCases.push(`    case ${slotNumber}: ${fn}(ctx, next); return true`);
    } else if (role === 'middleware') {
      declarations.push(`@external("pulsewasm_handlers", ${asString(field)})\ndeclare function ${fn}(ctx: usize, next: usize): void`);
      middlewareCases.push(`    case ${slotNumber}: ${fn}(ctx, next); return true`);
    } else if (role === 'route') {
      declarations.push(`@external("pulsewasm_handlers", ${asString(field)})\ndeclare function ${fn}(ctx: usize, next: usize): void`);
      routeCases.push(`    case ${slotNumber}: ${fn}(ctx, next); return true`);
    }
  }

  const declarationText = declarations.length > 0 ? declarations.join('\n\n') : '// No handler slots were emitted.';
  const routeCaseText = routeCases.length > 0 ? routeCases.join('\n') : '';
  const middlewareCaseText = middlewareCases.length > 0 ? middlewareCases.join('\n') : '';
  const lifecycleCaseText = lifecycleCases.length > 0 ? lifecycleCases.join('\n') : '';
  const errorCaseText = errorCases.length > 0 ? errorCases.join('\n') : '';
  const channelCaseText = channelCases.length > 0 ? channelCases.join('\n') : '';

  return `${header()}import {
  ROLE_ROUTE,
  ROLE_MIDDLEWARE,
  ROLE_LIFECYCLE,
  ROLE_ERROR,
  ROLE_CHANNEL
} from './types.as'

import {
  HANDLER_SLOT_COUNT,
  HANDLER_SLOT_IDS,
  HANDLER_SLOT_NAMES,
  HANDLER_ROLE_CODES,
  HANDLER_PARAM_COUNTS
} from './route-table.as'

// Phase 9C handler slot declarations.
// These are AssemblyScript import declarations. They bind dense handler slots to
// externally supplied/linked handler functions without re-reading user source.
${declarationText}

export const HANDLER_BINDINGS_MODULE: string = 'pulsewasm_handlers'
export const HANDLER_BINDING_COUNT: i32 = HANDLER_SLOT_COUNT

export function handlerSlotExists(slot: i32): bool {
  return slot >= 0 && slot < HANDLER_SLOT_COUNT
}

export function handlerIdForSlot(slot: i32): string {
  if (!handlerSlotExists(slot)) return ''
  return unchecked(HANDLER_SLOT_IDS[slot])
}

export function handlerNameForSlot(slot: i32): string {
  if (!handlerSlotExists(slot)) return ''
  return unchecked(HANDLER_SLOT_NAMES[slot])
}

export function handlerRoleCodeForSlot(slot: i32): i32 {
  if (!handlerSlotExists(slot)) return 0
  return unchecked(HANDLER_ROLE_CODES[slot])
}

export function handlerParamCountForSlot(slot: i32): i32 {
  if (!handlerSlotExists(slot)) return -1
  return unchecked(HANDLER_PARAM_COUNTS[slot])
}

export function slotAcceptsRole(slot: i32, roleCode: i32): bool {
  return handlerSlotExists(slot) && handlerRoleCodeForSlot(slot) == roleCode
}

export function invokeRouteHandlerBySlot(slot: i32, ctx: usize, next: usize): bool {
  if (!slotAcceptsRole(slot, ROLE_ROUTE)) return false
  switch (slot) {
${routeCaseText}
    default: return false
  }
}

export function invokeMiddlewareHandlerBySlot(slot: i32, ctx: usize, next: usize): bool {
  if (!slotAcceptsRole(slot, ROLE_MIDDLEWARE)) return false
  switch (slot) {
${middlewareCaseText}
    default: return false
  }
}

export function invokeLifecycleHandlerBySlot(slot: i32, ctx: usize, next: usize): bool {
  if (!slotAcceptsRole(slot, ROLE_LIFECYCLE)) return false
  switch (slot) {
${lifecycleCaseText}
    default: return false
  }
}

export function invokeErrorHandlerBySlot(slot: i32, err: usize, ctx: usize, next: usize): bool {
  if (!slotAcceptsRole(slot, ROLE_ERROR)) return false
  switch (slot) {
${errorCaseText}
    default: return false
  }
}

export function invokeChannelHandlerBySlot(slot: i32, ctx: usize): usize {
  if (!slotAcceptsRole(slot, ROLE_CHANNEL)) return 0
  switch (slot) {
${channelCaseText}
    default: return 0
  }
}

export function invokeHandlerByRole(roleCode: i32, slot: i32, err: usize, ctx: usize, next: usize): bool {
  if (roleCode == ROLE_ROUTE) return invokeRouteHandlerBySlot(slot, ctx, next)
  if (roleCode == ROLE_MIDDLEWARE) return invokeMiddlewareHandlerBySlot(slot, ctx, next)
  if (roleCode == ROLE_LIFECYCLE) return invokeLifecycleHandlerBySlot(slot, ctx, next)
  if (roleCode == ROLE_ERROR) return invokeErrorHandlerBySlot(slot, err, ctx, next)
  if (roleCode == ROLE_CHANNEL) return invokeChannelHandlerBySlot(slot, ctx) != 0
  return false
}
`;
}

function buildRuntimeCoreSource() {
  return `${header()}import {
  METHOD_UNKNOWN
} from './types.as'

import {
  EXECUTION_ENTRY_COUNT,
  ENTRY_KINDS,
  ENTRY_NEXT_INDICES,
  ENTRY_SCOPE_IDS,
  ENTRY_HANDLER_SLOTS,
  ENTRY_METHOD_CODES,
  ENTRY_ROUTE_RUNTIME_IDS,
  ENTRY_CHILD_START_INDICES,
  ENTRY_PARENT_CONTINUE_INDICES,
  SCOPE_COUNT,
  SCOPE_CHANNEL_KINDS,
  SCOPE_CHANNEL_SLOTS,
  SCOPE_CONNECT_OFFSETS,
  SCOPE_CONNECT_LENGTHS,
  SCOPE_CONNECT_SLOTS,
  SCOPE_DISCONNECT_OFFSETS,
  SCOPE_DISCONNECT_LENGTHS,
  SCOPE_DISCONNECT_SLOTS
} from './route-table.as'

import {
  PulseWasmParamsView,
  normalizeRequestPath,
  entryPathMatches,
  entryParamCount,
  entryParamNameAt,
  entryParamValueAt,
  entryParamValueStartAt,
  entryParamValueLengthAt,
  resetParamsView
} from './runtime-path.as'

import {
  invokeRouteHandlerBySlot,
  invokeMiddlewareHandlerBySlot,
  invokeErrorHandlerBySlot,
  invokeLifecycleHandlerBySlot,
  invokeChannelHandlerBySlot
} from './handler-slots.as'

// Entry kind ABI. Kept here so the scanner can be consumed without re-reading JSON metadata.
export const ENTRY_UNKNOWN: i32 = 0
export const ENTRY_USE: i32 = 1
export const ENTRY_ROUTE: i32 = 2
export const ENTRY_ERROR: i32 = 3
export const ENTRY_CHANNEL: i32 = 4
export const ENTRY_LIFECYCLE: i32 = 5
export const ENTRY_MOUNT: i32 = 6

// Scanner modes.
export const MODE_NORMAL: i32 = 0
export const MODE_ERROR: i32 = 1

// next() outcome contract.
export const NEXT_NONE: i32 = 0
export const NEXT_NORMAL: i32 = 1
export const NEXT_ERROR: i32 = 2

// Step result ABI.
export const STEP_DONE: i32 = 0
export const STEP_INVOKE: i32 = 1
export const STEP_NOT_FOUND: i32 = 2
export const STEP_UNHANDLED_ERROR: i32 = 3
export const STEP_INVALID: i32 = 4
export const STEP_CONTRACT_VIOLATION: i32 = 5

// Default result contract for exhausted chains / violations.
export const DEFAULT_STATUS_NOT_FOUND: i32 = 404
export const DEFAULT_STATUS_INTERNAL_ERROR: i32 = 500
export const DEFAULT_ERROR_NONE: string = ''
export const DEFAULT_ERROR_UNHANDLED: string = 'PULSEWASM_UNHANDLED_ERROR'
export const DEFAULT_ERROR_NO_RESULT: string = 'PULSEWASM_NO_RESULT'

export class PulseWasmErrorRef {
  code: string
  message: string
  statusCode: i32
  cause: usize

  constructor(code: string, message: string, statusCode: i32 = DEFAULT_STATUS_INTERNAL_ERROR, cause: usize = 0) {
    this.code = code
    this.message = message
    this.statusCode = statusCode
    this.cause = cause
  }
}

export class PulseWasmDispatchState {
  methodCode: i32
  requestPath: string
  mode: i32
  entryIndex: i32
  currentEntryIndex: i32
  currentKind: i32
  currentHandlerSlot: i32
  currentScopeId: i32
  currentRouteRuntimeId: i32
  activeError: usize
  resultRef: usize
  nextOutcome: i32
  params: PulseWasmParamsView
  stateKeys: Array<string>
  stateValues: Array<string>

  constructor(methodCode: i32, requestPath: string) {
    this.methodCode = methodCode
    this.requestPath = normalizeRequestPath(requestPath)
    this.mode = MODE_NORMAL
    this.entryIndex = 0
    this.currentEntryIndex = -1
    this.currentKind = ENTRY_UNKNOWN
    this.currentHandlerSlot = -1
    this.currentScopeId = -1
    this.currentRouteRuntimeId = -1
    this.activeError = 0
    this.resultRef = 0
    this.nextOutcome = NEXT_NONE
    this.params = new PulseWasmParamsView()
    this.stateKeys = new Array<string>()
    this.stateValues = new Array<string>()
  }
}

export function createPulseWasmError(code: string, message: string, statusCode: i32 = DEFAULT_STATUS_INTERNAL_ERROR, cause: usize = 0): PulseWasmErrorRef {
  return new PulseWasmErrorRef(code, message, statusCode, cause)
}

export function createDispatchState(methodCode: i32, requestPath: string): PulseWasmDispatchState {
  return new PulseWasmDispatchState(methodCode, requestPath)
}

export function resetDispatchState(state: PulseWasmDispatchState, methodCode: i32, requestPath: string): void {
  state.methodCode = methodCode
  state.requestPath = normalizeRequestPath(requestPath)
  state.mode = MODE_NORMAL
  state.entryIndex = 0
  state.currentEntryIndex = -1
  state.currentKind = ENTRY_UNKNOWN
  state.currentHandlerSlot = -1
  state.currentScopeId = -1
  state.currentRouteRuntimeId = -1
  state.activeError = 0
  state.resultRef = 0
  state.nextOutcome = NEXT_NONE
  resetParamsView(state.params, -1, state.requestPath)
  state.stateKeys.length = 0
  state.stateValues.length = 0
}

export function entryKindAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return ENTRY_UNKNOWN
  return unchecked(ENTRY_KINDS[entryIndex])
}

export function entryNextIndexAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return EXECUTION_ENTRY_COUNT
  const nextIndex = unchecked(ENTRY_NEXT_INDICES[entryIndex])
  if (nextIndex < 0) return EXECUTION_ENTRY_COUNT
  if (nextIndex > EXECUTION_ENTRY_COUNT) return EXECUTION_ENTRY_COUNT
  return nextIndex
}

export function entryHandlerSlotAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_HANDLER_SLOTS[entryIndex])
}

export function entryScopeIdAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_SCOPE_IDS[entryIndex])
}

export function entryRouteRuntimeIdAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_ROUTE_RUNTIME_IDS[entryIndex])
}

export function entryChildStartIndexAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_CHILD_START_INDICES[entryIndex])
}

export function entryParentContinueIndexAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_PARENT_CONTINUE_INDICES[entryIndex])
}

export function entryMatches(entryIndex: i32, mode: i32, methodCode: i32, requestPath: string): bool {
  const kind = entryKindAt(entryIndex)

  if (mode == MODE_ERROR) {
    return kind == ENTRY_ERROR
  }

  if (kind == ENTRY_ERROR || kind == ENTRY_CHANNEL || kind == ENTRY_LIFECYCLE) return false

  if (kind == ENTRY_USE) {
    return entryPathMatches(entryIndex, requestPath)
  }

  if (kind == ENTRY_ROUTE) {
    const routeMethod = unchecked(ENTRY_METHOD_CODES[entryIndex])
    return routeMethod == methodCode && entryPathMatches(entryIndex, requestPath)
  }

  if (kind == ENTRY_MOUNT) {
    return entryPathMatches(entryIndex, requestPath)
  }

  return false
}

export function scanNextEntry(startIndex: i32, mode: i32, methodCode: i32, requestPath: string): i32 {
  let index: i32 = startIndex
  const normalizedPath = normalizeRequestPath(requestPath)
  while (index >= 0 && index < EXECUTION_ENTRY_COUNT) {
    const kind = entryKindAt(index)

    if (mode == MODE_ERROR) {
      if (kind == ENTRY_ERROR) return index
      if (kind == ENTRY_MOUNT) {
        if (entryPathMatches(index, normalizedPath)) {
          const childStart = entryChildStartIndexAt(index)
          index = childStart >= 0 ? childStart : entryNextIndexAt(index)
        } else {
          const parentContinue = entryParentContinueIndexAt(index)
          index = parentContinue >= 0 ? parentContinue : entryNextIndexAt(index)
        }
        continue
      }
      index = entryNextIndexAt(index)
      continue
    }

    if (kind == ENTRY_MOUNT) {
      if (entryPathMatches(index, normalizedPath)) {
        const childStart = entryChildStartIndexAt(index)
        index = childStart >= 0 ? childStart : entryNextIndexAt(index)
      } else {
        const parentContinue = entryParentContinueIndexAt(index)
        index = parentContinue >= 0 ? parentContinue : entryNextIndexAt(index)
      }
      continue
    }

    if (entryMatches(index, mode, methodCode, normalizedPath)) return index
    index = entryNextIndexAt(index)
  }
  return -1
}

export function stepDispatchState(state: PulseWasmDispatchState): i32 {
  const nextEntry = scanNextEntry(state.entryIndex, state.mode, state.methodCode, state.requestPath)
  if (nextEntry < 0) {
    state.currentEntryIndex = -1
    state.currentKind = ENTRY_UNKNOWN
    state.currentHandlerSlot = -1
    state.currentScopeId = -1
    state.currentRouteRuntimeId = -1
    resetParamsView(state.params, -1, state.requestPath)
    return state.mode == MODE_ERROR ? STEP_UNHANDLED_ERROR : STEP_NOT_FOUND
  }

  state.currentEntryIndex = nextEntry
  state.currentKind = entryKindAt(nextEntry)
  state.currentHandlerSlot = entryHandlerSlotAt(nextEntry)
  state.currentScopeId = entryScopeIdAt(nextEntry)
  state.currentRouteRuntimeId = entryRouteRuntimeIdAt(nextEntry)
  resetParamsView(state.params, nextEntry, state.requestPath)
  return STEP_INVOKE
}

export function continueNormal(state: PulseWasmDispatchState): void {
  const from = state.currentEntryIndex >= 0 ? state.currentEntryIndex : state.entryIndex
  state.mode = MODE_NORMAL
  state.activeError = 0
  state.nextOutcome = NEXT_NORMAL
  state.entryIndex = entryNextIndexAt(from)
  state.currentEntryIndex = -1
  state.currentKind = ENTRY_UNKNOWN
  state.currentHandlerSlot = -1
  state.currentRouteRuntimeId = -1
}

export function continueError(state: PulseWasmDispatchState, errorRef: usize): void {
  const from = state.currentEntryIndex >= 0 ? state.currentEntryIndex : state.entryIndex
  state.mode = MODE_ERROR
  state.activeError = errorRef
  state.nextOutcome = NEXT_ERROR
  state.entryIndex = entryNextIndexAt(from)
  state.currentEntryIndex = -1
  state.currentKind = ENTRY_UNKNOWN
  state.currentHandlerSlot = -1
  state.currentRouteRuntimeId = -1
}

export function pulse_next(state: PulseWasmDispatchState): void {
  continueNormal(state)
}

export function pulse_next_error(state: PulseWasmDispatchState, errorRef: usize): void {
  continueError(state, errorRef)
}

export function pulse_set_result(state: PulseWasmDispatchState, resultRef: usize): void {
  state.resultRef = resultRef
  state.nextOutcome = NEXT_NONE
  haltDispatchState(state)
}

export function haltDispatchState(state: PulseWasmDispatchState): void {
  state.entryIndex = EXECUTION_ENTRY_COUNT
  state.currentEntryIndex = -1
  state.currentKind = ENTRY_UNKNOWN
  state.currentHandlerSlot = -1
  state.currentRouteRuntimeId = -1
}

export function defaultStatusForStepResult(stepResult: i32): i32 {
  if (stepResult == STEP_NOT_FOUND) return DEFAULT_STATUS_NOT_FOUND
  if (stepResult == STEP_UNHANDLED_ERROR) return DEFAULT_STATUS_INTERNAL_ERROR
  if (stepResult == STEP_CONTRACT_VIOLATION) return DEFAULT_STATUS_INTERNAL_ERROR
  return 0
}

export function defaultErrorCodeForStepResult(stepResult: i32): string {
  if (stepResult == STEP_UNHANDLED_ERROR) return DEFAULT_ERROR_UNHANDLED
  if (stepResult == STEP_CONTRACT_VIOLATION) return DEFAULT_ERROR_NO_RESULT
  return DEFAULT_ERROR_NONE
}

export function currentParamCount(state: PulseWasmDispatchState): i32 {
  return state.params.count
}

export function currentParamNameAt(state: PulseWasmDispatchState, paramIndex: i32): string {
  return entryParamNameAt(state.currentEntryIndex, paramIndex)
}

export function currentParamValueAt(state: PulseWasmDispatchState, paramIndex: i32): string {
  return entryParamValueAt(state.currentEntryIndex, state.requestPath, paramIndex)
}

export function currentParamValueStartAt(state: PulseWasmDispatchState, paramIndex: i32): i32 {
  return entryParamValueStartAt(state.currentEntryIndex, state.requestPath, paramIndex)
}

export function currentParamValueLengthAt(state: PulseWasmDispatchState, paramIndex: i32): i32 {
  return entryParamValueLengthAt(state.currentEntryIndex, state.requestPath, paramIndex)
}

export function matchFirstRouteRuntimeId(methodCode: i32, requestPath: string): i32 {
  const normalizedPath = normalizeRequestPath(requestPath)
  let index = scanNextEntry(0, MODE_NORMAL, methodCode, normalizedPath)
  while (index >= 0) {
    if (entryKindAt(index) == ENTRY_ROUTE) return entryRouteRuntimeIdAt(index)
    index = scanNextEntry(entryNextIndexAt(index), MODE_NORMAL, methodCode, normalizedPath)
  }
  return -1
}

export function matchRouteId(methodCode: i32, requestPath: string): i32 {
  return matchFirstRouteRuntimeId(methodCode, requestPath)
}

export function scopeChannelKind(scopeId: i32): i32 {
  if (scopeId < 0 || scopeId >= SCOPE_COUNT) return 0
  return unchecked(SCOPE_CHANNEL_KINDS[scopeId])
}

export function scopeChannelSlot(scopeId: i32): i32 {
  if (scopeId < 0 || scopeId >= SCOPE_COUNT) return -1
  return unchecked(SCOPE_CHANNEL_SLOTS[scopeId])
}

export function scopeConnectLength(scopeId: i32): i32 {
  if (scopeId < 0 || scopeId >= SCOPE_COUNT) return 0
  return unchecked(SCOPE_CONNECT_LENGTHS[scopeId])
}

export function scopeConnectSlotAt(scopeId: i32, index: i32): i32 {
  if (scopeId < 0 || scopeId >= SCOPE_COUNT) return -1
  const length = unchecked(SCOPE_CONNECT_LENGTHS[scopeId])
  if (index < 0 || index >= length) return -1
  const offset = unchecked(SCOPE_CONNECT_OFFSETS[scopeId])
  return unchecked(SCOPE_CONNECT_SLOTS[offset + index])
}

export function scopeDisconnectLength(scopeId: i32): i32 {
  if (scopeId < 0 || scopeId >= SCOPE_COUNT) return 0
  return unchecked(SCOPE_DISCONNECT_LENGTHS[scopeId])
}

export function scopeDisconnectSlotAt(scopeId: i32, index: i32): i32 {
  if (scopeId < 0 || scopeId >= SCOPE_COUNT) return -1
  const length = unchecked(SCOPE_DISCONNECT_LENGTHS[scopeId])
  if (index < 0 || index >= length) return -1
  const offset = unchecked(SCOPE_DISCONNECT_OFFSETS[scopeId])
  return unchecked(SCOPE_DISCONNECT_SLOTS[offset + index])
}

// Phase 9C handler invocation wrappers.
// Concrete handler bodies are still external/linked through generated handler slot imports.
export function invokeRouteHandler(slot: i32, ctx: usize, next: usize): bool {
  return invokeRouteHandlerBySlot(slot, ctx, next)
}

export function invokeMiddlewareHandler(slot: i32, ctx: usize, next: usize): bool {
  return invokeMiddlewareHandlerBySlot(slot, ctx, next)
}

export function invokeErrorHandler(slot: i32, err: usize, ctx: usize, next: usize): bool {
  return invokeErrorHandlerBySlot(slot, err, ctx, next)
}

export function invokeLifecycleHandler(slot: i32, ctx: usize, next: usize): bool {
  return invokeLifecycleHandlerBySlot(slot, ctx, next)
}

export function invokeChannelHandler(slot: i32, ctx: usize): usize {
  return invokeChannelHandlerBySlot(slot, ctx)
}

export function invokeCurrentHandlerWithRefs(state: PulseWasmDispatchState, ctx: usize, next: usize): bool {
  if (state.currentHandlerSlot < 0) return false
  if (state.currentKind == ENTRY_USE) return invokeMiddlewareHandler(state.currentHandlerSlot, ctx, next)
  if (state.currentKind == ENTRY_ROUTE) return invokeRouteHandler(state.currentHandlerSlot, ctx, next)
  if (state.currentKind == ENTRY_ERROR) return invokeErrorHandler(state.currentHandlerSlot, state.activeError, ctx, next)
  if (state.currentKind == ENTRY_LIFECYCLE) return invokeLifecycleHandler(state.currentHandlerSlot, ctx, next)
  return false
}

export function invokeCurrentHandler(state: PulseWasmDispatchState): bool {
  const stateRef = changetype<usize>(state)
  return invokeCurrentHandlerWithRefs(state, stateRef, stateRef)
}
`;
}

function buildTypeConstantExports() {
  return [
    'METHOD_UNKNOWN',
    'METHOD_GET',
    'METHOD_POST',
    'METHOD_PUT',
    'METHOD_PATCH',
    'METHOD_DELETE',
    'METHOD_HEAD',
    'METHOD_OPTIONS',
    'SEGMENT_UNKNOWN',
    'SEGMENT_LITERAL',
    'SEGMENT_PARAM',
    'SEGMENT_WILDCARD',
    'CHANNEL_NONE',
    'CHANNEL_STATIC',
    'CHANNEL_HANDLER',
    'ROLE_UNKNOWN',
    'ROLE_ROUTE',
    'ROLE_MIDDLEWARE',
    'ROLE_LIFECYCLE',
    'ROLE_ERROR',
    'ROLE_CHANNEL'
  ];
}

function buildRuntimePathExports() {
  return [
    'resetParamsView',
    'normalizeRequestPath',
    'requestPathIsValid',
    'pathSegmentCount',
    'pathSegmentStartAt',
    'pathSegmentEndAt',
    'pathSegmentLengthAt',
    'pathSegmentAt',
    'entryPatternSegmentCount',
    'entryPatternSegmentKindAt',
    'entryPatternSegmentValueAt',
    'entryHasWildcard',
    'entryPathMatches',
    'entryParamCount',
    'entryParamNameAt',
    'entryParamValueStartAt',
    'entryParamValueLengthAt',
    'entryParamValueAt',
    'paramsNameAt',
    'paramsValueStartAt',
    'paramsValueLengthAt',
    'paramsValueAt',
    'paramsValueByName',
    'entryWildcardRestStartAt',
    'entryWildcardRestAt'
  ];
}

function buildRuntimeCoreExports() {
  return [
    'ENTRY_UNKNOWN',
    'ENTRY_USE',
    'ENTRY_ROUTE',
    'ENTRY_ERROR',
    'ENTRY_CHANNEL',
    'ENTRY_LIFECYCLE',
    'ENTRY_MOUNT',
    'MODE_NORMAL',
    'MODE_ERROR',
    'NEXT_NONE',
    'NEXT_NORMAL',
    'NEXT_ERROR',
    'STEP_DONE',
    'STEP_INVOKE',
    'STEP_NOT_FOUND',
    'STEP_UNHANDLED_ERROR',
    'STEP_INVALID',
    'STEP_CONTRACT_VIOLATION',
    'DEFAULT_STATUS_NOT_FOUND',
    'DEFAULT_STATUS_INTERNAL_ERROR',
    'DEFAULT_ERROR_NONE',
    'DEFAULT_ERROR_UNHANDLED',
    'DEFAULT_ERROR_NO_RESULT',
    'createPulseWasmError',
    'createDispatchState',
    'resetDispatchState',
    'entryKindAt',
    'entryNextIndexAt',
    'entryHandlerSlotAt',
    'entryScopeIdAt',
    'entryRouteRuntimeIdAt',
    'entryChildStartIndexAt',
    'entryParentContinueIndexAt',
    'entryMatches',
    'scanNextEntry',
    'stepDispatchState',
    'continueNormal',
    'continueError',
    'pulse_next',
    'pulse_next_error',
    'pulse_set_result',
    'haltDispatchState',
    'defaultStatusForStepResult',
    'defaultErrorCodeForStepResult',
    'currentParamCount',
    'currentParamNameAt',
    'currentParamValueAt',
    'currentParamValueStartAt',
    'currentParamValueLengthAt',
    'matchFirstRouteRuntimeId',
    'matchRouteId',
    'scopeChannelKind',
    'scopeChannelSlot',
    'scopeConnectLength',
    'scopeConnectSlotAt',
    'scopeDisconnectLength',
    'scopeDisconnectSlotAt',
    'invokeRouteHandler',
    'invokeMiddlewareHandler',
    'invokeErrorHandler',
    'invokeLifecycleHandler',
    'invokeChannelHandler',
    'invokeCurrentHandlerWithRefs',
    'invokeCurrentHandler'
  ];
}


function buildDispatchShapeExports() {
  return [
    'routeIndexForRuntimeId',
    'methodCodeForRouteIndex',
    'handlerSlotForRouteIndex',
    'normalChainLengthForRouteIndex',
    'normalChainSlotAt'
  ];
}

function namedExportBlock(names, from) {
  return `export {\n  ${names.join(',\n  ')}\n} from '${from}'\n`;
}

function buildCoreIndexSource() {
  return `${header()}${namedExportBlock(buildTypeConstantExports(), './types.as')}export * from './route-table.as'
${namedExportBlock(buildDispatchShapeExports(), './dispatch-shape.as')}${namedExportBlock(buildRuntimePathExports(), './runtime-path.as')}export * from './handler-slots.as'
${namedExportBlock(buildRuntimeCoreExports(), './runtime-core.as')}`;
}

function buildAssemblyScriptCore(dispatchTable, options = {}) {
  const cwd = options.cwd || process.cwd();
  const executionPlan = options.executionPlan;
  const shape = options.assemblyScriptShape;

  const handlerSlots = sortHandlerSlots(dispatchTable);
  const files = [
    makeFile('generated/as/runtime-path.as.ts', buildRuntimePathSource()),
    makeFile('generated/as/handler-slots.as.ts', buildHandlerSlotsSource(dispatchTable)),
    makeFile('generated/as/runtime-core.as.ts', buildRuntimeCoreSource()),
    makeFile('generated/as/index.as.ts', buildCoreIndexSource())
  ];

  const artifact = normalizeArtifact({
    version: ASSEMBLYSCRIPT_CORE_VERSION,
    generatedBy: options.generatedBy || PACKAGE_VERSION,
    source: dispatchTable?.source,
    sourceDispatchTableVersion: dispatchTable?.version,
    executionPlanVersion: executionPlan?.version,
    assemblyScriptShapeVersion: shape?.artifact?.version,
    policy: {
      phase: '9C',
      sourceOfTruth: 'execution-plan.json + generated ENTRY_* tables',
      reReadsSource: false,
      reInfersRouteSemantics: false,
      wasmCodegen: false,
      assemblyScriptCompilerInvocation: false,
      runtimeCore: true,
      pathMatcher: true,
      executionModel: 'ordered entry scanner with full request path matching and static nextIndex continuations',
      continuationModel: 'next() and next(err) mutate PulseWasmDispatchState integers; no JS closures',
      handlerInvocation: 'generated handler slot imports and role-specific slot switch dispatch; concrete handler body lowering remains outside Phase 9C',
      hostBindings: 'not emitted; WIT/wasi/http bindings remain outside Phase 9C'
    },
    runtimeContract: {
      ctxAbi: {
        kind: 'resettable dispatch state, not singleton ctx',
        requestPath: 'full request path string stored on PulseWasmDispatchState.requestPath',
        params: 'PulseWasmParamsView backed by compiled param names and request-path start/length slices',
        resultRef: 'usize result handle, 0 when no result exists yet',
        activeError: 'usize error handle, 0 when no active error exists'
      },
      nextOutcomes: {
        none: 0,
        normal: 1,
        error: 2
      },
      fallthrough: {
        normal: { statusCode: 404, meaning: 'full normal chain exhausted with no result' },
        error: { statusCode: 500, meaning: 'error mode exhausted with active error and no result' },
        contractViolation: { statusCode: 500, code: 'PULSEWASM_NO_RESULT' }
      },
      errorShape: {
        code: 'mandatory string',
        message: 'mandatory string',
        statusCode: 'mandatory i32, default 500',
        cause: 'optional usize, 0 when absent'
      },
      mountPathPolicy: 'full request path is canonical; child/parent flow uses execution-plan indices, not trimmed relative paths'
    },
    abi: {
      state: 'PulseWasmDispatchState',
      paramsView: 'PulseWasmParamsView',
      error: 'PulseWasmErrorRef',
      modes: {
        normal: 0,
        error: 1
      },
      stepResults: {
        done: 0,
        invoke: 1,
        notFound: 2,
        unhandledError: 3,
        invalid: 4,
        contractViolation: 5
      },
      exportedFunctions: [
        'normalizeRequestPath(path: string): string',
        'requestPathIsValid(path: string): bool',
        'pathSegmentCount(path: string): i32',
        'pathSegmentStartAt(path: string, index: i32): i32',
        'pathSegmentLengthAt(path: string, index: i32): i32',
        'entryPathMatches(entryIndex: i32, requestPath: string): bool',
        'entryParamNameAt(entryIndex: i32, paramIndex: i32): string',
        'entryParamValueStartAt(entryIndex: i32, requestPath: string, paramIndex: i32): i32',
        'entryParamValueLengthAt(entryIndex: i32, requestPath: string, paramIndex: i32): i32',
        'entryParamValueAt(entryIndex: i32, requestPath: string, paramIndex: i32): string',
        'createDispatchState(methodCode: i32, requestPath: string): PulseWasmDispatchState',
        'resetDispatchState(state: PulseWasmDispatchState, methodCode: i32, requestPath: string): void',
        'stepDispatchState(state: PulseWasmDispatchState): i32',
        'pulse_next(state: PulseWasmDispatchState): void',
        'pulse_next_error(state: PulseWasmDispatchState, errorRef: usize): void',
        'pulse_set_result(state: PulseWasmDispatchState, resultRef: usize): void',
        'defaultStatusForStepResult(stepResult: i32): i32',
        'matchRouteId(methodCode: i32, requestPath: string): i32',
        'invokeRouteHandler(slot: i32, ctx: usize, next: usize): bool',
        'invokeMiddlewareHandler(slot: i32, ctx: usize, next: usize): bool',
        'invokeErrorHandler(slot: i32, err: usize, ctx: usize, next: usize): bool',
        'invokeLifecycleHandler(slot: i32, ctx: usize, next: usize): bool',
        'invokeChannelHandler(slot: i32, ctx: usize): usize',
        'invokeCurrentHandler(state: PulseWasmDispatchState): bool'
      ]
    },
    generated: {
      language: 'assemblyscript',
      module: 'esm',
      directory: 'generated/as',
      files: files.map(({ file, bytes, sha256: hash }) => ({ file, bytes, sha256: hash }))
    },
    summary: {
      routes: Array.isArray(dispatchTable?.routes) ? dispatchTable.routes.length : 0,
      entries: Array.isArray(executionPlan?.entries) ? executionPlan.entries.length : 0,
      executableEntries: executionPlan?.summary?.executableEntries || 0,
      scopes: Array.isArray(executionPlan?.scopes) ? executionPlan.scopes.length : 0,
      handlerSlots: Array.isArray(dispatchTable?.handlerSlots) ? dispatchTable.handlerSlots.length : 0,
      files: files.length,
      scannerImplemented: true,
      pathMatcherImplemented: true,
      handlerSlotInvokerImplemented: true,
      pathMatcherParity: true,
      fullPathMatching: true,
      paramsOffsetBacked: true,
      ctxAbiV1: true,
      fallthroughContractLocked: true,
      continuationRuntimeImplemented: true,
      handlerInvocationStubs: false,
      handlerSlotBindings: true,
      wasmEmitted: false
    }
  }, cwd);

  const handlersArtifact = normalizeArtifact({
    version: ASSEMBLYSCRIPT_HANDLERS_VERSION,
    generatedBy: options.generatedBy || PACKAGE_VERSION,
    source: dispatchTable?.source,
    sourceDispatchTableVersion: dispatchTable?.version,
    policy: {
      phase: '9C',
      sourceOfTruth: 'dispatch-table.json handlerSlots + generated route-table handler metadata',
      reReadsSource: false,
      reInfersRouteSemantics: false,
      importsModule: 'pulsewasm_handlers',
      handlerBodiesLowered: false,
      wasmCodegen: false,
      assemblyScriptCompilerInvocation: false
    },
    slots: handlerSlots.map((slot) => ({
      slot: slot.slot,
      id: slot.id,
      name: slot.name,
      external: handlerExternalField(slot),
      symbol: handlerExternalName(slot),
      role: handlerBaseRole(slot),
      roles: slot.roles || [],
      paramCount: slot.signature?.paramCount,
      source: slot.file
    })),
    summary: {
      handlerSlots: handlerSlots.length,
      routeHandlers: handlerSlots.filter((slot) => handlerBaseRole(slot) == 'route').length,
      middlewareHandlers: handlerSlots.filter((slot) => handlerBaseRole(slot) == 'middleware').length,
      lifecycleHandlers: handlerSlots.filter((slot) => handlerBaseRole(slot) == 'lifecycle').length,
      errorHandlers: handlerSlots.filter((slot) => handlerBaseRole(slot) == 'error').length,
      channelHandlers: handlerSlots.filter((slot) => handlerBaseRole(slot) == 'channel').length,
      generatedFile: 'generated/as/handler-slots.as.ts',
      bindingsModule: 'pulsewasm_handlers'
    }
  }, cwd);

  return {
    version: ASSEMBLYSCRIPT_CORE_VERSION,
    artifact,
    handlersArtifact,
    files,
    diagnostics: []
  };
}

module.exports = {
  ASSEMBLYSCRIPT_CORE_VERSION,
  ASSEMBLYSCRIPT_HANDLERS_VERSION,
  buildAssemblyScriptCore
};
