'use strict';

function loadContractsDiagnostics() {
  try {
    return require('@pulse-compute/wasm-contracts/diagnostics');
  } catch (error) {
    if (error && error.code === 'MODULE_NOT_FOUND' && String(error.message).includes('@pulse-compute/wasm-contracts')) {
      return require('../../../contracts/src/diagnostics.js');
    }
    throw error;
  }
}

const crypto = require('node:crypto');
const { PACKAGE_VERSION, normalizeArtifact } = loadContractsDiagnostics();
const { ENTRY_KIND_CODES } = loadContractsExecutionPlan();

const ASSEMBLYSCRIPT_SHAPE_VERSION = 'pulsewasm.assemblyscript-shape.v2';
const ASSEMBLYSCRIPT_GENERATED_MANIFEST_VERSION = 'pulsewasm.assemblyscript-generated.v2';

const METHOD_CODES = Object.freeze({
  GET: 1,
  POST: 2,
  PUT: 3,
  PATCH: 4,
  DELETE: 5,
  HEAD: 6,
  OPTIONS: 7
});

const SEGMENT_CODES = Object.freeze({
  literal: 1,
  param: 2,
  wildcard: 3
});

const CHANNEL_CODES = Object.freeze({
  none: 0,
  static: 1,
  handler: 2
});

const ROLE_CODES = Object.freeze({
  route: 1,
  middleware: 2,
  lifecycle: 3,
  error: 4,
  channel: 5
});

function loadContractsExecutionPlan() {
  try {
    return require('@pulse-compute/wasm-contracts/execution-plan');
  } catch (error) {
    if (error && error.code === 'MODULE_NOT_FOUND' && String(error.message).includes('@pulse-compute/wasm-contracts')) {
      return require('../../../contracts/src/execution-plan.js');
    }
    throw error;
  }
}

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

function json(value) {
  return JSON.stringify(value, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');
}

function asString(value) {
  return JSON.stringify(String(value ?? ''));
}

function asI32Array(values) {
  return `StaticArray.fromArray<i32>([${values.map((value) => Number(value) | 0).join(', ')}])`;
}

function asStringArray(values) {
  return `StaticArray.fromArray<string>([${values.map(asString).join(', ')}])`;
}

function header(phase = '8D') {
  return [
    '/*',
    ` * Generated by PulseWasm Phase ${phase}.`,
    ' * Do not edit by hand.',
    ' *',
    ' * This is an AssemblyScript shape artifact, not a compiled Wasm output.',
    ' * It is generated from dispatch-table.json and must not re-read source.',
    ' */',
    ''
  ].join('\n');
}

function makeFile(file, text) {
  return {
    file,
    bytes: Buffer.byteLength(text, 'utf8'),
    sha256: sha256(text),
    text
  };
}

function methodCode(method) {
  return METHOD_CODES[String(method || '').toUpperCase()] || 0;
}

function segmentCode(segment) {
  return SEGMENT_CODES[segment?.kind] || 0;
}

function channelCode(channel) {
  if (!channel) return CHANNEL_CODES.none;
  if (channel.kind === 'handler') return CHANNEL_CODES.handler;
  if (channel.kind === 'static') return CHANNEL_CODES.static;
  return CHANNEL_CODES.none;
}

function roleCode(role) {
  const base = String(role || '').split(':')[0];
  return ROLE_CODES[base] || 0;
}

function slotsFromSteps(steps) {
  return (steps || [])
    .map((step) => step?.slot)
    .filter((slot) => Number.isInteger(slot));
}

function flattenLists(lists) {
  const offsets = [];
  const lengths = [];
  const values = [];
  for (const list of lists) {
    offsets.push(values.length);
    lengths.push(list.length);
    values.push(...list);
  }
  return { offsets, lengths, values };
}

function collectShapeTables(dispatchTable, executionPlan) {
  const routes = (dispatchTable?.routes || []).slice().sort((a, b) => Number(a.runtimeId) - Number(b.runtimeId));
  const handlerSlots = (dispatchTable?.handlerSlots || []).slice().sort((a, b) => Number(a.slot) - Number(b.slot));

  const routeRuntimeIds = routes.map((route) => route.runtimeId);
  const routeStableIds = routes.map((route) => route.stableId);
  const routeMethodCodes = routes.map((route) => methodCode(route.method));
  const routeMethods = routes.map((route) => route.method);
  const routePaths = routes.map((route) => route.path);
  const routeHandlerSlots = routes.map((route) => Number(route.handlers?.route?.slot ?? -1));
  const routeWildcardFlags = routes.map((route) => route.pattern?.wildcard ? 1 : 0);

  const segmentLists = routes.map((route) => route.pattern?.segments || []);
  const segmentOffsets = [];
  const segmentLengths = [];
  const segmentKinds = [];
  const segmentValues = [];
  for (const segments of segmentLists) {
    segmentOffsets.push(segmentKinds.length);
    segmentLengths.push(segments.length);
    for (const segment of segments) {
      segmentKinds.push(segmentCode(segment));
      segmentValues.push(segment.kind === 'param' ? segment.name : segment.value || '');
    }
  }

  const paramLists = routes.map((route) => route.params || []);
  const params = flattenLists(paramLists);

  const normalChains = flattenLists(routes.map((route) => slotsFromSteps(route.execution?.normal)));
  const errorChains = flattenLists(routes.map((route) => slotsFromSteps(route.execution?.error)));
  const connectChains = flattenLists(routes.map((route) => slotsFromSteps(route.execution?.lifecycle?.connect)));
  const disconnectChains = flattenLists(routes.map((route) => slotsFromSteps(route.execution?.lifecycle?.disconnect)));

  const routeChannelKinds = routes.map((route) => channelCode(route.execution?.channel));
  const routeChannelSlots = routes.map((route) => route.execution?.channel?.kind === 'handler' ? Number(route.execution.channel.slot ?? -1) : -1);
  const routeChannelStaticValues = routes.map((route) => route.execution?.channel?.kind === 'static' ? String(route.execution.channel.value || '') : '');

  const handlerSlotIds = handlerSlots.map((slot) => slot.id);
  const handlerSlotNames = handlerSlots.map((slot) => slot.name || slot.id);
  const handlerRoleCodes = handlerSlots.map((slot) => roleCode((slot.roles || [])[0]));
  const handlerParamCounts = handlerSlots.map((slot) => Number(slot.signature?.paramCount ?? -1));

  const executionEntries = Array.isArray(executionPlan?.entries) ? executionPlan.entries : [];
  const executionScopes = Array.isArray(executionPlan?.scopes) ? executionPlan.scopes : [];
  const entryKinds = executionEntries.map((entry) => ENTRY_KIND_CODES[entry.kind] || 0);
  const entryNextIndices = executionEntries.map((entry) => Number.isInteger(entry.nextIndex) ? entry.nextIndex : -1);
  const entryScopeIds = executionEntries.map((entry) => Number.isInteger(entry.scopeId) ? entry.scopeId : -1);
  const entryHandlerSlots = executionEntries.map((entry) => Number.isInteger(entry.handler?.slot) ? entry.handler.slot : -1);
  const entryMethodCodes = executionEntries.map((entry) => entry.method ? methodCode(entry.method) : 0);
  const entryRouteRuntimeIds = executionEntries.map((entry) => Number.isInteger(entry.runtimeId) ? entry.runtimeId : -1);
  const entryChildStartIndices = executionEntries.map((entry) => Number.isInteger(entry.childStartIndex) ? entry.childStartIndex : -1);
  const entryParentContinueIndices = executionEntries.map((entry) => Number.isInteger(entry.parentContinueIndex) ? entry.parentContinueIndex : -1);
  const entryPatternLists = executionEntries.map((entry) => entry.pattern?.segments || []);
  const entrySegmentOffsets = [];
  const entrySegmentLengths = [];
  const entrySegmentKinds = [];
  const entrySegmentValues = [];
  for (const segments of entryPatternLists) {
    entrySegmentOffsets.push(entrySegmentKinds.length);
    entrySegmentLengths.push(segments.length);
    for (const segment of segments) {
      entrySegmentKinds.push(segmentCode(segment));
      entrySegmentValues.push(segment.kind === 'param' ? segment.name : segment.value || '');
    }
  }
  const scopeChannelKinds = executionScopes.map((scope) => channelCode(scope.channel));
  const scopeChannelSlots = executionScopes.map((scope) => scope.channel?.kind === 'handler' ? Number(scope.channel.slot ?? -1) : -1);
  const scopeConnect = flattenLists(executionScopes.map((scope) => slotsFromSteps(scope.connect)));
  const scopeDisconnect = flattenLists(executionScopes.map((scope) => slotsFromSteps(scope.disconnect)));

  return {
    routeRuntimeIds,
    routeStableIds,
    routeMethodCodes,
    routeMethods,
    routePaths,
    routeHandlerSlots,
    routeWildcardFlags,
    segmentOffsets,
    segmentLengths,
    segmentKinds,
    segmentValues,
    paramOffsets: params.offsets,
    paramLengths: params.lengths,
    paramNames: params.values,
    normalChainOffsets: normalChains.offsets,
    normalChainLengths: normalChains.lengths,
    normalChainSlots: normalChains.values,
    errorChainOffsets: errorChains.offsets,
    errorChainLengths: errorChains.lengths,
    errorChainSlots: errorChains.values,
    connectChainOffsets: connectChains.offsets,
    connectChainLengths: connectChains.lengths,
    connectChainSlots: connectChains.values,
    disconnectChainOffsets: disconnectChains.offsets,
    disconnectChainLengths: disconnectChains.lengths,
    disconnectChainSlots: disconnectChains.values,
    routeChannelKinds,
    routeChannelSlots,
    routeChannelStaticValues,
    handlerSlotIds,
    handlerSlotNames,
    handlerRoleCodes,
    handlerParamCounts,
    methodCodes: METHOD_CODES,
    segmentCodes: SEGMENT_CODES,
    channelCodes: CHANNEL_CODES,
    roleCodes: ROLE_CODES,
    entryKindCodes: ENTRY_KIND_CODES,
    entryKinds,
    entryNextIndices,
    entryScopeIds,
    entryHandlerSlots,
    entryMethodCodes,
    entryRouteRuntimeIds,
    entryChildStartIndices,
    entryParentContinueIndices,
    entrySegmentOffsets,
    entrySegmentLengths,
    entrySegmentKinds,
    entrySegmentValues,
    scopeChannelKinds,
    scopeChannelSlots,
    scopeConnectOffsets: scopeConnect.offsets,
    scopeConnectLengths: scopeConnect.lengths,
    scopeConnectSlots: scopeConnect.values,
    scopeDisconnectOffsets: scopeDisconnect.offsets,
    scopeDisconnectLengths: scopeDisconnect.lengths,
    scopeDisconnectSlots: scopeDisconnect.values,
    routeRecords: routes.map((route) => ({
      runtimeId: route.runtimeId,
      stableId: route.stableId,
      method: route.method,
      methodCode: methodCode(route.method),
      path: route.path,
      params: route.params || [],
      handlerSlot: Number(route.handlers?.route?.slot ?? -1),
      normalSlots: slotsFromSteps(route.execution?.normal),
      errorSlots: slotsFromSteps(route.execution?.error),
      connectSlots: slotsFromSteps(route.execution?.lifecycle?.connect),
      disconnectSlots: slotsFromSteps(route.execution?.lifecycle?.disconnect),
      channel: route.execution?.channel || { kind: 'none' }
    })),
    handlerRecords: handlerSlots.map((slot) => ({
      slot: slot.slot,
      id: slot.id,
      name: slot.name,
      roles: slot.roles || [],
      roleCodes: (slot.roles || []).map(roleCode),
      signature: slot.signature,
      eval: slot.eval
    }))
  };
}

function buildTypesSource() {
  return `${header()}// Numeric ABI constants for generated AssemblyScript tables.
export const METHOD_UNKNOWN: i32 = 0
export const METHOD_GET: i32 = 1
export const METHOD_POST: i32 = 2
export const METHOD_PUT: i32 = 3
export const METHOD_PATCH: i32 = 4
export const METHOD_DELETE: i32 = 5
export const METHOD_HEAD: i32 = 6
export const METHOD_OPTIONS: i32 = 7

export const SEGMENT_UNKNOWN: i32 = 0
export const SEGMENT_LITERAL: i32 = 1
export const SEGMENT_PARAM: i32 = 2
export const SEGMENT_WILDCARD: i32 = 3

export const CHANNEL_NONE: i32 = 0
export const CHANNEL_STATIC: i32 = 1
export const CHANNEL_HANDLER: i32 = 2

export const ROLE_UNKNOWN: i32 = 0
export const ROLE_ROUTE: i32 = 1
export const ROLE_MIDDLEWARE: i32 = 2
export const ROLE_LIFECYCLE: i32 = 3
export const ROLE_ERROR: i32 = 4
export const ROLE_CHANNEL: i32 = 5

export type RouteRuntimeId = i32
export type HandlerSlot = i32
export type MethodCode = i32
export type SegmentKind = i32
export type ChannelKind = i32

// Planned handler ABI. Concrete imports/exports are reserved for Phase 9.
export type RouteHandler = (ctx: usize, next: usize) => void
export type MiddlewareHandler = (ctx: usize, next: usize) => void
export type LifecycleHandler = (ctx: usize, next: usize) => void
export type ErrorHandler = (err: usize, ctx: usize, next: usize) => void
export type ChannelHandler = (ctx: usize) => usize
`;
}

function buildRouteTableSource(tables) {
  return `${header()}import {
  METHOD_GET,
  METHOD_POST,
  SEGMENT_LITERAL,
  SEGMENT_PARAM,
  SEGMENT_WILDCARD,
  CHANNEL_NONE,
  CHANNEL_STATIC,
  CHANNEL_HANDLER
} from './types.as'

export const ROUTE_COUNT: i32 = ${tables.routeRuntimeIds.length}
export const HANDLER_SLOT_COUNT: i32 = ${tables.handlerSlotIds.length}

export const ROUTE_RUNTIME_IDS: StaticArray<i32> = ${asI32Array(tables.routeRuntimeIds)}
export const ROUTE_METHOD_CODES: StaticArray<i32> = ${asI32Array(tables.routeMethodCodes)}
export const ROUTE_PATHS: StaticArray<string> = ${asStringArray(tables.routePaths)}
export const ROUTE_STABLE_IDS: StaticArray<string> = ${asStringArray(tables.routeStableIds)}
export const ROUTE_HANDLER_SLOTS: StaticArray<i32> = ${asI32Array(tables.routeHandlerSlots)}
export const ROUTE_WILDCARD_FLAGS: StaticArray<i32> = ${asI32Array(tables.routeWildcardFlags)}

export const ROUTE_SEGMENT_OFFSETS: StaticArray<i32> = ${asI32Array(tables.segmentOffsets)}
export const ROUTE_SEGMENT_LENGTHS: StaticArray<i32> = ${asI32Array(tables.segmentLengths)}
export const SEGMENT_KINDS: StaticArray<i32> = ${asI32Array(tables.segmentKinds)}
export const SEGMENT_VALUES: StaticArray<string> = ${asStringArray(tables.segmentValues)}

export const ROUTE_PARAM_OFFSETS: StaticArray<i32> = ${asI32Array(tables.paramOffsets)}
export const ROUTE_PARAM_LENGTHS: StaticArray<i32> = ${asI32Array(tables.paramLengths)}
export const PARAM_NAMES: StaticArray<string> = ${asStringArray(tables.paramNames)}

export const NORMAL_CHAIN_OFFSETS: StaticArray<i32> = ${asI32Array(tables.normalChainOffsets)}
export const NORMAL_CHAIN_LENGTHS: StaticArray<i32> = ${asI32Array(tables.normalChainLengths)}
export const NORMAL_CHAIN_SLOTS: StaticArray<i32> = ${asI32Array(tables.normalChainSlots)}

export const ERROR_CHAIN_OFFSETS: StaticArray<i32> = ${asI32Array(tables.errorChainOffsets)}
export const ERROR_CHAIN_LENGTHS: StaticArray<i32> = ${asI32Array(tables.errorChainLengths)}
export const ERROR_CHAIN_SLOTS: StaticArray<i32> = ${asI32Array(tables.errorChainSlots)}

export const CONNECT_CHAIN_OFFSETS: StaticArray<i32> = ${asI32Array(tables.connectChainOffsets)}
export const CONNECT_CHAIN_LENGTHS: StaticArray<i32> = ${asI32Array(tables.connectChainLengths)}
export const CONNECT_CHAIN_SLOTS: StaticArray<i32> = ${asI32Array(tables.connectChainSlots)}

export const DISCONNECT_CHAIN_OFFSETS: StaticArray<i32> = ${asI32Array(tables.disconnectChainOffsets)}
export const DISCONNECT_CHAIN_LENGTHS: StaticArray<i32> = ${asI32Array(tables.disconnectChainLengths)}
export const DISCONNECT_CHAIN_SLOTS: StaticArray<i32> = ${asI32Array(tables.disconnectChainSlots)}

export const ROUTE_CHANNEL_KINDS: StaticArray<i32> = ${asI32Array(tables.routeChannelKinds)}
export const ROUTE_CHANNEL_SLOTS: StaticArray<i32> = ${asI32Array(tables.routeChannelSlots)}
export const ROUTE_CHANNEL_STATIC_VALUES: StaticArray<string> = ${asStringArray(tables.routeChannelStaticValues)}

export const HANDLER_SLOT_IDS: StaticArray<string> = ${asStringArray(tables.handlerSlotIds)}
export const HANDLER_SLOT_NAMES: StaticArray<string> = ${asStringArray(tables.handlerSlotNames)}
export const HANDLER_ROLE_CODES: StaticArray<i32> = ${asI32Array(tables.handlerRoleCodes)}
export const HANDLER_PARAM_COUNTS: StaticArray<i32> = ${asI32Array(tables.handlerParamCounts)}

// Phase 8E canonical execution-plan entry scanner tables.
export const EXECUTION_ENTRY_COUNT: i32 = ${tables.entryKinds.length}
export const ENTRY_KINDS: StaticArray<i32> = ${asI32Array(tables.entryKinds)}
export const ENTRY_NEXT_INDICES: StaticArray<i32> = ${asI32Array(tables.entryNextIndices)}
export const ENTRY_SCOPE_IDS: StaticArray<i32> = ${asI32Array(tables.entryScopeIds)}
export const ENTRY_HANDLER_SLOTS: StaticArray<i32> = ${asI32Array(tables.entryHandlerSlots)}
export const ENTRY_METHOD_CODES: StaticArray<i32> = ${asI32Array(tables.entryMethodCodes)}
export const ENTRY_ROUTE_RUNTIME_IDS: StaticArray<i32> = ${asI32Array(tables.entryRouteRuntimeIds)}
export const ENTRY_CHILD_START_INDICES: StaticArray<i32> = ${asI32Array(tables.entryChildStartIndices)}
export const ENTRY_PARENT_CONTINUE_INDICES: StaticArray<i32> = ${asI32Array(tables.entryParentContinueIndices)}
export const ENTRY_SEGMENT_OFFSETS: StaticArray<i32> = ${asI32Array(tables.entrySegmentOffsets)}
export const ENTRY_SEGMENT_LENGTHS: StaticArray<i32> = ${asI32Array(tables.entrySegmentLengths)}
export const ENTRY_SEGMENT_KINDS: StaticArray<i32> = ${asI32Array(tables.entrySegmentKinds)}
export const ENTRY_SEGMENT_VALUES: StaticArray<string> = ${asStringArray(tables.entrySegmentValues)}

export const SCOPE_COUNT: i32 = ${tables.scopeChannelKinds.length}
export const SCOPE_CHANNEL_KINDS: StaticArray<i32> = ${asI32Array(tables.scopeChannelKinds)}
export const SCOPE_CHANNEL_SLOTS: StaticArray<i32> = ${asI32Array(tables.scopeChannelSlots)}
export const SCOPE_CONNECT_OFFSETS: StaticArray<i32> = ${asI32Array(tables.scopeConnectOffsets)}
export const SCOPE_CONNECT_LENGTHS: StaticArray<i32> = ${asI32Array(tables.scopeConnectLengths)}
export const SCOPE_CONNECT_SLOTS: StaticArray<i32> = ${asI32Array(tables.scopeConnectSlots)}
export const SCOPE_DISCONNECT_OFFSETS: StaticArray<i32> = ${asI32Array(tables.scopeDisconnectOffsets)}
export const SCOPE_DISCONNECT_LENGTHS: StaticArray<i32> = ${asI32Array(tables.scopeDisconnectLengths)}
export const SCOPE_DISCONNECT_SLOTS: StaticArray<i32> = ${asI32Array(tables.scopeDisconnectSlots)}
`;
}

function buildDispatchShapeSource() {
  return `${header()}import {
  ROUTE_COUNT,
  ROUTE_RUNTIME_IDS,
  ROUTE_METHOD_CODES,
  ROUTE_HANDLER_SLOTS,
  NORMAL_CHAIN_OFFSETS,
  NORMAL_CHAIN_LENGTHS,
  NORMAL_CHAIN_SLOTS,
  EXECUTION_ENTRY_COUNT,
  ENTRY_KINDS,
  ENTRY_NEXT_INDICES,
  ENTRY_HANDLER_SLOTS,
  ENTRY_SCOPE_IDS
} from './route-table.as'

// Phase 8E deliberately stops at entry-state-machine shape planning.
// Phase 9 owns concrete AssemblyScript matching, handler imports, and Wasm compilation.

export function routeIndexForRuntimeId(runtimeId: i32): i32 {
  for (let i: i32 = 0; i < ROUTE_COUNT; i++) {
    if (unchecked(ROUTE_RUNTIME_IDS[i]) == runtimeId) return i
  }
  return -1
}

export function methodCodeForRouteIndex(routeIndex: i32): i32 {
  if (routeIndex < 0 || routeIndex >= ROUTE_COUNT) return 0
  return unchecked(ROUTE_METHOD_CODES[routeIndex])
}

export function handlerSlotForRouteIndex(routeIndex: i32): i32 {
  if (routeIndex < 0 || routeIndex >= ROUTE_COUNT) return -1
  return unchecked(ROUTE_HANDLER_SLOTS[routeIndex])
}

export function normalChainLengthForRouteIndex(routeIndex: i32): i32 {
  if (routeIndex < 0 || routeIndex >= ROUTE_COUNT) return 0
  return unchecked(NORMAL_CHAIN_LENGTHS[routeIndex])
}

export function normalChainSlotAt(routeIndex: i32, chainIndex: i32): i32 {
  if (routeIndex < 0 || routeIndex >= ROUTE_COUNT) return -1
  const length = unchecked(NORMAL_CHAIN_LENGTHS[routeIndex])
  if (chainIndex < 0 || chainIndex >= length) return -1
  const offset = unchecked(NORMAL_CHAIN_OFFSETS[routeIndex])
  return unchecked(NORMAL_CHAIN_SLOTS[offset + chainIndex])
}

export function entryKindAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return 0
  return unchecked(ENTRY_KINDS[entryIndex])
}

export function entryNextIndexAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_NEXT_INDICES[entryIndex])
}

export function entryHandlerSlotAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_HANDLER_SLOTS[entryIndex])
}

export function entryScopeIdAt(entryIndex: i32): i32 {
  if (entryIndex < 0 || entryIndex >= EXECUTION_ENTRY_COUNT) return -1
  return unchecked(ENTRY_SCOPE_IDS[entryIndex])
}

export function matchRouteId(methodCode: i32, path: string): i32 {
  // Shape-only placeholder. Concrete path matching is Phase 9.
  // Phase 9 should scan ENTRY_* tables, not reconstruct nested Router objects.
  return -1
}
`;
}

function buildTypeConstantExports() {
  return [
    'METHOD_UNKNOWN',
    'METHOD_GET',
    'METHOD_POST',
    'METHOD_PUT',
    'METHOD_PATCH',
    'METHOD_DELETE',
    'METHOD_HEAD',
    'METHOD_OPTIONS',
    'SEGMENT_UNKNOWN',
    'SEGMENT_LITERAL',
    'SEGMENT_PARAM',
    'SEGMENT_WILDCARD',
    'CHANNEL_NONE',
    'CHANNEL_STATIC',
    'CHANNEL_HANDLER',
    'ROLE_UNKNOWN',
    'ROLE_ROUTE',
    'ROLE_MIDDLEWARE',
    'ROLE_LIFECYCLE',
    'ROLE_ERROR',
    'ROLE_CHANNEL'
  ];
}

function namedExportBlock(names, from) {
  return `export {\n  ${names.join(',\n  ')}\n} from '${from}'\n`;
}

function buildIndexSource() {
  return `${header()}${namedExportBlock(buildTypeConstantExports(), './types.as')}export * from './route-table.as'\nexport * from './dispatch-shape.as'\n`;
}

function buildAssemblyScriptShape(dispatchTable, options = {}) {
  const cwd = options.cwd || process.cwd();
  const executionPlan = options.executionPlan;
  const tables = collectShapeTables(dispatchTable, executionPlan);

  const files = [
    makeFile('generated/as/types.as.ts', buildTypesSource()),
    makeFile('generated/as/route-table.as.ts', buildRouteTableSource(tables)),
    makeFile('generated/as/dispatch-shape.as.ts', buildDispatchShapeSource()),
    makeFile('generated/as/index.as.ts', buildIndexSource())
  ];

  const manifest = normalizeArtifact({
    version: ASSEMBLYSCRIPT_GENERATED_MANIFEST_VERSION,
    generatedBy: options.generatedBy || PACKAGE_VERSION,
    source: dispatchTable?.source,
    sourceDispatchTableVersion: dispatchTable?.version,
    output: {
      language: 'assemblyscript',
      module: 'esm',
      directory: 'generated/as',
      files: files.map(({ file, bytes, sha256: hash }) => ({ file, bytes, sha256: hash }))
    },
    policy: {
      phase: '8E',
      sourceOfTruth: 'dispatch-table.json + execution-plan.json',
      reReadsSource: false,
      reInfersRouteSemantics: false,
      wasmCodegen: false,
      assemblyScriptCompilerInvocation: false,
      executionModel: 'ordered entry scanner with static nextIndex continuations',
      handlerImports: 'planned only; concrete AssemblyScript handler import/export binding is reserved for Phase 9',
      hostBindings: 'not emitted; WIT/wasi/http bindings remain outside Phase 8E'
    },
    summary: {
      routes: tables.routeRuntimeIds.length,
      entries: tables.entryKinds.length,
      scopes: tables.scopeChannelKinds.length,
      handlerSlots: tables.handlerSlotIds.length,
      methods: Array.from(new Set(tables.routeMethods)).sort(),
      normalChainLinks: tables.normalChainSlots.length,
      errorChainLinks: tables.errorChainSlots.length,
      lifecycleLinks: tables.connectChainSlots.length + tables.disconnectChainSlots.length,
      channelHandlers: tables.routeChannelKinds.filter((kind) => kind === CHANNEL_CODES.handler).length,
      staticChannels: tables.routeChannelKinds.filter((kind) => kind === CHANNEL_CODES.static).length,
      files: files.length
    }
  }, cwd);

  const artifact = normalizeArtifact({
    version: ASSEMBLYSCRIPT_SHAPE_VERSION,
    generatedBy: options.generatedBy || PACKAGE_VERSION,
    source: dispatchTable?.source,
    sourceDispatchTableVersion: dispatchTable?.version,
    executionPlanVersion: executionPlan?.version,
    routePlanVersion: dispatchTable?.routePlanVersion,
    handlerTableVersion: dispatchTable?.handlerTableVersion,
    handlerEvalVersion: dispatchTable?.handlerEvalVersion,
    pathTableVersion: dispatchTable?.pathTableVersion,
    policy: {
      phase: '8E',
      sourceOfTruth: 'dispatch-table.json + execution-plan.json',
      reReadsSource: false,
      reInfersRouteSemantics: false,
      tableLayout: 'flat static arrays with offset/length pairs plus execution entry scanner tables',
      runtimeSemanticsChanged: false,
      generatedDispatchExecutes: false,
      wasmCodegen: false,
      assemblyScriptCompilerInvocation: false
    },
    abi: {
      language: 'AssemblyScript',
      plannedIntegerTypes: {
        runtimeId: 'i32',
        handlerSlot: 'i32',
        methodCode: 'i32',
        segmentKind: 'i32',
        channelKind: 'i32',
        roleCode: 'i32'
      },
      handlerSignatures: {
        route: '(ctx: usize, next: usize) => void',
        middleware: '(ctx: usize, next: usize) => void',
        lifecycle: '(ctx: usize, next: usize) => void',
        error: '(err: usize, ctx: usize, next: usize) => void',
        channel: '(ctx: usize) => usize'
      },
      exportedFunctionsPlanned: [
        'routeIndexForRuntimeId(runtimeId: i32): i32',
        'methodCodeForRouteIndex(routeIndex: i32): i32',
        'handlerSlotForRouteIndex(routeIndex: i32): i32',
        'normalChainLengthForRouteIndex(routeIndex: i32): i32',
        'normalChainSlotAt(routeIndex: i32, chainIndex: i32): i32',
        'entryKindAt(entryIndex: i32): i32',
        'entryNextIndexAt(entryIndex: i32): i32',
        'entryHandlerSlotAt(entryIndex: i32): i32',
        'entryScopeIdAt(entryIndex: i32): i32',
        'matchRouteId(methodCode: i32, path: string): i32'
      ]
    },
    codes: {
      methods: METHOD_CODES,
      segments: SEGMENT_CODES,
      channels: CHANNEL_CODES,
      roles: ROLE_CODES
    },
    tables,
    generated: manifest.output,
    compilationGates: {
      completed: [
        'route topology flattened',
        'stable route IDs assigned',
        'handler roles/signatures classified',
        'async/promise/generator handlers rejected',
        'handler dependency validator completed',
        'path metadata normalized',
        'dispatch metadata emitted',
        'runtime-parity execution plan emitted'
      ],
      pendingForPhase9: [
        'AssemblyScript entry-state-machine implementation for next()/next(err)',
        'AssemblyScript handler body subset verification',
        'concrete handler import/export binding for AssemblyScript',
        'AssemblyScript path matcher implementation',
        'middleware/error/lifecycle invocation implementation in AssemblyScript',
        'host/WIT/wasi:http boundary definition',
        'asc/compiler invocation and wasm artifact emission'
      ]
    },
    summary: manifest.summary
  }, cwd);

  return {
    version: ASSEMBLYSCRIPT_SHAPE_VERSION,
    artifact,
    manifest,
    files,
    diagnostics: []
  };
}

module.exports = {
  ASSEMBLYSCRIPT_SHAPE_VERSION,
  ASSEMBLYSCRIPT_GENERATED_MANIFEST_VERSION,
  METHOD_CODES,
  SEGMENT_CODES,
  CHANNEL_CODES,
  ROLE_CODES,
  ENTRY_KIND_CODES,
  collectShapeTables,
  buildAssemblyScriptShape
};
