'use strict';

const {
  runtimeContract, eventContract, CanonicalNativeAssemblyScriptError,
  stableHash, quote, prepareNativePlan, prepareNativeEmissionInputs, prepareNativeFlow
} = require('./canonical-native-context.js');
const { nativeSchemaCodecSource } = require('./canonical-native-schema.js');
const { buildNativeCryptoGuestSources } = require('./crypto-guest-source.js');
const {
  prepareNativeRuntimeSupport, renderNativeValueSupport,
  renderNativeResumeSupport, renderNativeExports
} = require('./canonical-native-support.js');

const { prepareNativeExpressions } = require('./canonical-native-expressions.js');
const {
  buildNativeControl, layoutNativeControl, countNativeGuardStates, renderNativeRun
} = require('./canonical-native-control.js');

const CANONICAL_NATIVE_AS_GENERATOR_VERSION = runtimeContract.CANONICAL_NATIVE_AS_GENERATOR_VERSION;

function generateCanonicalNativeAssemblyScript(plan, options = {}) {
  const {
    pureHelpers, stages, stageBindings, stageSites, maxStageSites,
    localIndex, effectIndex, continuationIndex, expressions, expressionIndex,
    stateEnabled, binaryIndex, unaryIndex, fail, localName, stringHandle
  } = prepareNativePlan(plan);
  const nativeSchemaCodecs = nativeSchemaCodecSource(plan);
  const nativeCrypto = buildNativeCryptoGuestSources(plan);
  const { eventEntries, eventReachable } = prepareNativeEmissionInputs(plan);
  const expressionEmitter = prepareNativeExpressions({
    expressions, expressionIndex, pureHelpers, localIndex, binaryIndex, unaryIndex,
    fail, localName, stringHandle
  });
  const { applicationErrors, helpers, handlers, routerLocal, routerCursor } = prepareNativeFlow(plan, pureHelpers);
  const control = buildNativeControl({
    plan, stages, stageBindings, stageSites, effectIndex, continuationIndex,
    applicationErrors, helpers, handlers, routerLocal, routerCursor,
    exprName: expressionEmitter.exprName, localName, stringHandle, fail
  });
  const layout = layoutNativeControl({
    blocks: control.blocks, stages, helpers, handlers, applicationErrors,
    routerLocal, routerCursor, localName, fail
  });
  const support = prepareNativeRuntimeSupport({
    plan, stages, stageSites, maxStageSites, helpers, applicationErrors,
    stateEnabled, eventEntries, eventReachable,
    blocks: control.blocks, resumeRequirements: control.resumeRequirements
  });
  const guardStateCount = countNativeGuardStates({
    plan, blocks: control.blocks, handlers, helpers, stages, fail
  });
  const source = assembleNativeSource({
    plan, nativeSchemaCodecs, nativeCrypto, support, expressionEmitter,
    stages, stageSites, stateEnabled, binaryIndex, eventReachable,
    entryBlock: control.entryBlock, layout, guardStateCount
  });
  return assembleNativeResult({
    plan, source, nativeSchemaCodecs, nativeCrypto, expressions, pureHelpers,
    stages, helpers, handlers, stateEnabled, eventReachable, eventEntries,
    control, layout, guardStateCount
  });
}

function assembleNativeSource({
  plan, nativeSchemaCodecs, nativeCrypto, support, expressionEmitter,
  stages, stageSites, stateEnabled, binaryIndex, eventReachable,
  entryBlock, layout, guardStateCount
}) {
  const { errorGuard, dispatcherFunctions, partitioned, renderedBlocks, invalidProgramCounter } = layout;
  return [
    '/* Generated by Pulse canonical native AssemblyScript compiler. */',
    ...nativeSchemaCodecs.imports,
    ...(nativeSchemaCodecs.imports.length > 0 ? [''] : []),
    ...support.imports,
    '',
    `const PULSE_ABI_VERSION: i32 = ${runtimeContract.CANONICAL_NATIVE_ABI_VERSION}`,
    `const PULSE_PLAN_HASH: string = ${quote(plan.planHash)}`,
    `const PULSE_ENTRY_PC: i32 = ${entryBlock}`,
    ...support.executionGlobals,
    ...support.globals,
    ...renderNativeValueSupport({ stages, stageSites, stateEnabled, binaryIndex }),
    ...nativeSchemaCodecs.declarations,
    ...(nativeCrypto.active ? [nativeCrypto.source] : []),
    ...expressionEmitter.renderDeclarations(),
    ...renderNativeResumeSupport(support),
    ...errorGuard,
    ...dispatcherFunctions,
    ...renderNativeRun({ guardStateCount, partitioned, renderedBlocks, invalidProgramCounter }),
    ...renderNativeExports({ eventReachable, stateEnabled, eventExports: support.eventExports, setterCases: support.setterCases }),
    ...nativeSchemaCodecs.exports,
    ''
  ].join('\n');
}

function assembleNativeResult({
  plan, source, nativeSchemaCodecs, nativeCrypto, expressions, pureHelpers,
  stages, helpers, handlers, stateEnabled, eventReachable, eventEntries,
  control, layout, guardStateCount
}) {
  const { blocks, entryBlock, stageEntries, helperEntries } = control;
  const { partitioned, chunks, renderedBlocks, maxChunkStates, maxChunkCharacters } = layout;
  const manifest = Object.freeze({
    version: runtimeContract.CANONICAL_NATIVE_WASM_VERSION,
    generatorVersion: CANONICAL_NATIVE_AS_GENERATOR_VERSION,
    abiVersion: runtimeContract.CANONICAL_NATIVE_ABI_VERSION,
    planVersion: plan.version,
    planHash: plan.planHash,
    sourceHash: stableHash(source),
    entryBlock,
    blockCount: blocks.length,
    guardStateCount,
    dispatcher: Object.freeze({
      strategy: partitioned ? 'bounded-state-chunks' : 'single-function',
      chunkCount: chunks.length,
      maxChunkStates,
      maxChunkCharacters,
      oversizedStateCount: (partitioned ? chunks.flat() : renderedBlocks).filter(block => block.source.length > maxChunkCharacters).length,
      guard: 'shared-once-per-state',
      chunkInlining: partitioned ? 'disabled' : 'not-applicable'
    }),
    stages: Object.freeze([...stages.values()].map(stage => Object.freeze({
      id: stage.id, handlerId: stage.handlerId, registrations: stage.registrations.length,
      entryBlock: stageEntries.get(stage.id), bodyStates: blocks.filter(block => block.handlerId === stage.id).length,
      chunks: Object.freeze(chunks.flatMap((chunk, index) => chunk[0].handlerId === stage.id ? [index] : []))
    }))),
    pureHelperBodies: Object.freeze([...pureHelpers.values()].map(helper => Object.freeze({ id: helper.id, name: helper.nativeName }))),
    helperBodies: Object.freeze([...helpers.values()].map(helper => Object.freeze({
      id: helper.id, entryBlock: helperEntries.get(helper.id), bodyStates: blocks.filter(b => b.handlerId === helper.id).length,
      chunks: Object.freeze(chunks.flatMap((chunk, i) => chunk[0].handlerId === helper.id ? [i] : []))
    }))),
    handlerBodies: Object.freeze([...handlers.values()].map(handler => Object.freeze({
      id: handler.id,
      handlerId: handler.handlerId,
      chunks: Object.freeze(chunks.flatMap((chunk, index) => chunk[0].handlerId === handler.id ? [index] : [])),
      stateCount: blocks.filter(block => block.handlerId === handler.id).length
    }))),
    expressionCount: expressions.length,
    localCount: (plan.locals || []).length,
    schemaCodecs: Object.freeze({
      active: nativeSchemaCodecs.active,
      backend: nativeSchemaCodecs.active ? 'json-as' : 'none',
      package: nativeSchemaCodecs.active ? 'json-as' : null,
      packageVersion: nativeSchemaCodecs.active ? '1.5.0' : null,
      registryHash: plan.schemas && plan.schemas.registryHash || null,
      codecTableHash: plan.schemas && plan.schemas.codecTableHash || null,
      sourceHash: nativeSchemaCodecs.sourceHash,
      codecs: nativeSchemaCodecs.codecs
    }),
    crypto: Object.freeze({
      version: nativeCrypto.version,
      active: nativeCrypto.active,
      realizationPlanVersion: nativeCrypto.realizationPlanVersion,
      realizationPlanHash: nativeCrypto.realizationPlanHash,
      algorithms: nativeCrypto.algorithms,
      sourceHash: nativeCrypto.sourceHash,
      automaticFallback: false
    }),
    requestState: Object.freeze({
      enabled: stateEnabled,
      representation: stateEnabled ? 'guest-string-map' : 'absent',
      reset: stateEnabled ? (eventReachable ? 'invocation-start' : 'pulse-start') : 'not-required'
    }),
    ...(eventReachable ? {
      events: Object.freeze({
        version: eventContract.EVENT_NATIVE_ABI_EXTENSION_VERSION,
        abiVersion: eventContract.EVENT_NATIVE_ABI_EXTENSION.abiVersion,
        catalogHash: plan.events.catalog.catalogHash,
        count: eventEntries.length,
        exports: eventContract.EVENT_NATIVE_ABI_EXTENSION.exports,
        imports: eventContract.EVENT_NATIVE_ABI_EXTENSION.imports,
        selection: 'artifact-local-runtime-id',
        payload: 'host-owned-schema-validated-value-handle',
        completion: eventContract.EVENT_COMPLETION_SEMANTICS
      })
    } : {}),
    ...(plan.application ? { application: plan.application } : {}),
    ...(plan.json ? { json: plan.json } : {}),
    effectCount: (plan.effects || []).length,
    continuationCount: (plan.continuations || []).length,
    allowedImports: runtimeContract.CANONICAL_NATIVE_IMPORTS,
    requiredExports: eventReachable
      ? Object.freeze([...runtimeContract.CANONICAL_NATIVE_EXPORTS, ...eventContract.EVENT_NATIVE_ABI_EXTENSION.exports])
      : runtimeContract.CANONICAL_NATIVE_EXPORTS,
    policy: Object.freeze({ ...runtimeContract.CANONICAL_NATIVE_POLICY,
      ...(plan.capabilities.includes('request.body.transform') ? { bodyTransform: { version: 'pulse.bounded-text-transform.v1', inputBytes: 65536, outputBytes: 262144, maxExpansionRatio: 4, encoding: 'utf-8-fatal', memory: runtimeContract.CANONICAL_NATIVE_READ_LOOP_MEMORY } } : {}),
      ...(plan.capabilities.includes('response.output') ? { generatedOutput: { version: 'pulse.generated-output.v1', memory: runtimeContract.CANONICAL_NATIVE_READ_LOOP_MEMORY, completion: 'provider-local-finish', independentInstalledQualification: false } } : {}),
      ...(runtimeContract.hasBoundedReadLoop(plan) ? { readLoopMemory: runtimeContract.CANONICAL_NATIVE_READ_LOOP_MEMORY } : {}) })
  });

  return Object.freeze({
    version: CANONICAL_NATIVE_AS_GENERATOR_VERSION,
    source,
    sourceHash: manifest.sourceHash,
    manifest,
    blocks: Object.freeze(blocks.map((item) => Object.freeze({ ...item })))
  });
}

module.exports = Object.freeze({
  CANONICAL_NATIVE_AS_GENERATOR_VERSION,
  CanonicalNativeAssemblyScriptError,
  generateCanonicalNativeAssemblyScript
});
