'use strict';

// Canonical schema owner. The checked-in JSON schemas are generated by the
// contract test's explicit --write-fixtures mode, never edited independently.
const { LIMITS, freeze } = require('./data');
const str = { type: 'string', maxLength: LIMITS.stringBytes };
const text = { ...str, minLength: 1 };
const id = { type: 'string', pattern: '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$' };
const hash = { type: 'string', pattern: '^[a-f0-9]{64}$' };
const uint = { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER };
const bool = { type: 'boolean' };
const en = (...values) => ({ enum: values });
const fixed = value => ({ const: value });
const ref = name => ({ $ref: '#/$defs/' + name });
const nullable = schema => ({ anyOf: [schema, { type: 'null' }] });
const array = items => ({ type: 'array', items, maxItems: LIMITS.records });
const object = (properties, optional = []) => ({ type: 'object', properties,
  required: Object.keys(properties).filter(key => !optional.includes(key)), additionalProperties: false });
const ids = array(id);
// Report-local failure vocabulary; capture emits only these codes and counters.
const GRAPH_DIAGNOSTICS = Object.freeze({
  'table': 'unsupported-table-control', 'element-segment': 'unsupported-table-control',
  'indirect-call': 'unsupported-indirect-control', 'reference-control': 'unsupported-reference-control',
  'tail-call': 'unsupported-tail-call',
  'import-name': 'unresolved-function-identity', 'function-index': 'unresolved-function-identity',
  'function-name': 'unresolved-function-identity', 'duplicate-name': 'unresolved-function-identity',
  'direct-target': 'unresolved-function-identity',
  'malformed-text': 'graph-parser-mismatch', 'import-count': 'graph-parser-mismatch',
  'definition-count': 'graph-parser-mismatch', 'direct-call-shape': 'graph-parser-mismatch',
  'direct-call-scope': 'graph-parser-mismatch', 'binaryen-read': 'graph-parser-mismatch',
  'binaryen-text': 'graph-parser-mismatch', 'unexpected-parser-failure': 'graph-parser-mismatch',
  'text-byte-limit': 'graph-budget-exhausted', 'function-limit': 'graph-budget-exhausted',
  'edge-limit': 'graph-budget-exhausted', 'traversal-work-limit': 'graph-budget-exhausted',
  'capture-absent': 'missing-evidence', 'prelink-evidence-only': 'prelink-only'
});
const REASONS = ['missing-evidence', 'unsupported-mapping', 'incomplete-mapping', 'incomplete-root-universe',
  'unsupported-call-graph', 'prelink-only', 'not-recorded', 'not-applicable', 'unsupported-schema-shape',
  'unsupported-schema-version', 'unsupported-constraint', 'upstream-partial',
  'entry-ownership-not-retained', 'dispatcher-carrier', 'final-symbol-not-surviving', 'dynamic-reference', 'unresolved-reference',
  ...new Set(Object.values(GRAPH_DIAGNOSTICS).filter(reason => !['missing-evidence', 'prelink-only'].includes(reason)))];
const BODY_KINDS = ['terminal-body', 'shared-stage-body', 'shared-helper-body', 'dispatcher-carrier'];
const ENTRY_ROLES = ['route', 'middleware', 'fallback', 'error', 'event', 'startup', 'export', 'other'];
const RESOURCE_SCOPES = ['selected-embedded-assets', 'schema-codecs', 'package-guest-units', 'package-realizations', 'generated-support', 'canonical-text-responses'];
const defs = {
  ResourceProducer: object({ scope: en(...RESOURCE_SCOPES), producer: ref('Producer'), coverage: ref('Coverage'), resourceIds: ids, evidenceIds: ids }),
  ResourceGenerator: object({ scope: en(...RESOURCE_SCOPES), producer: ref('Producer'),
    representation: en('base64-text', 'pulse.report-schema-shape.v1', 'package-guest-unit', 'native-string'),
    representationBytes: ref('Fact'), schemaId: nullable(id), entryCoverage: ref('Coverage') }),
  GraphDiagnostic: object({ reason: en(...new Set(Object.values(GRAPH_DIAGNOSTICS))), code: en(...Object.keys(GRAPH_DIAGNOSTICS)),
    functionIndex: nullable(uint), observed: nullable(uint), expected: nullable(uint) }),
  Source: object({ file: text, line: { ...uint, minimum: 1 }, column: { ...uint, minimum: 1 },
    endLine: { ...uint, minimum: 1 }, endColumn: { ...uint, minimum: 1 } }, ['endLine', 'endColumn']),
  Coverage: object({ status: en('complete', 'partial', 'unavailable', 'not-applicable'),
    observed: uint, expected: nullable(uint), reason: nullable(en(...REASONS)) }),
  Fact: object({ state: en('available', 'unavailable', 'not-applicable'),
    basis: en('declared', 'resolved', 'measured', 'recorded'), coverage: en('exact', 'bounded', 'partial'),
    value: nullable(uint), reason: nullable(en(...REASONS)), evidenceIds: ids }),
  Producer: object({ name: text, version: text }),
  File: object({ file: text, bytes: uint, sha256: hash }),
  Context: object({ profile: text, host: text, target: fixed('native'), representation: fixed('canonical-native-wasm'), primaryArtifactId: id }),
  Recipe: object({ name: text, version: text, optimization: en('default', 'experimental-native-size', 'experimental-native-bounded-size', 'unavailable'), guestLinked: bool }),
  Route: object({ id, canonicalId: text, order: uint, method: text, path: str, handlerId: id,
    handlerName: nullable(str), entryId: id, source: nullable(ref('Source')), composition: ids,
    compositionCoverage: en('complete', 'bounded', 'unavailable'),
    schemaIds: ids, bindingIds: ids, declarationIds: ids, evidenceIds: ids }, ['compositionCoverage']),
  Entry: object({ id, canonicalId: text, kind: en(...ENTRY_ROLES),
    order: uint, handlerId: nullable(id), name: nullable(str), source: nullable(ref('Source')),
    schemaIds: ids, bindingIds: ids, declarationIds: ids, evidenceIds: ids,
    flow: object({ nextEntryId: nullable(id), childEntryId: nullable(id), parentContinueEntryId: nullable(id),
      routerPath: array(text), path: nullable(str), method: nullable(text), scoped: bool, conditional: bool }) }, ['flow']),
  Declaration: object({ id, kind: text, name: str, evidenceIds: ids }),
  Node: { oneOf: [
    object({ kind: en('string', 'boolean', 'i32', 'u32', 'f64', 'json-value', 'json-object') }),
    object({ kind: fixed('string-enum'), literalCount: { ...uint, minimum: 1 } }),
    object({ kind: fixed('scalar-record'), limits: ref('ScalarLimits') }),
    object({ kind: fixed('array'), element: ref('Node') }),
    object({ kind: fixed('nullable'), value: ref('Node') }),
    object({ kind: fixed('object'), fields: array(object({ name: text, required: bool, value: ref('Node') })), additionalProperties: bool })
  ] },
  ScalarLimits: object(Object.fromEntries(['maxKeys', 'maxKeyLength', 'maxStringLength', 'maxBytes', 'numberBytes'].map(key => [key, { ...uint, minimum: 1 }]))),
  JsonLimits: object(Object.fromEntries(['maxTextBytes', 'maxDepth', 'maxNodes', 'maxObjectMembers', 'maxArrayItems', 'maxKeyLength', 'maxStringLength', 'maxJsonBytes'].map(key => [key, { ...uint, minimum: 1 }]))),
  Descriptor: object({ representation: fixed('pulse.report-schema-shape.v1'), root: ref('Node'), jsonLimits: nullable(ref('JsonLimits')) }),
  Structure: object({ representation: fixed('pulse.report-schema-shape.v1'), state: en('available', 'unavailable'),
    reason: nullable(en(...REASONS)), descriptor: nullable(ref('Descriptor')), descriptorBytes: nullable(uint),
    keyCountsState: en('available', 'unavailable', 'not-applicable'), topLevelKeys: nullable(uint), requiredKeys: nullable(uint),
    properties: array(object({ name: text, type: text, required: nullable(bool) })) }),
  Schema: object({ id, schemaId: text, registryVersion: text, source: nullable(ref('Source')),
    structure: ref('Structure'), routeIds: ids, entryIds: ids, evidenceIds: ids }),
  Binding: object({ id, name: text, kind: text, declared: bool, referenced: bool,
    resolution: en('bound', 'unbound', 'unavailable'), routeIds: ids, entryIds: ids, evidenceIds: ids }),
  Reference: object({ id, kind: en('binding', 'schema', 'resource'), bindingKind: nullable(en('config', 'secret', 'kv', 's3')),
    canonicalId: nullable(text), state: en('resolved', 'dynamic', 'unknown'), reason: nullable(en(...REASONS)),
    targetId: nullable(id), entryIds: ids, entryCoverage: ref('Coverage'), evidenceIds: ids,
    externalPackages: { ...array(text), minItems: 1, uniqueItems: true } }, ['externalPackages']),
  Resource: object({ id, name: text, kind: en('embedded-asset', 'schema-validator', 'helper', 'other', 'response-payload'),
    mediaType: nullable(text), artifactId: nullable(id), inputBytes: ref('Fact'), retainedPayloadBytes: ref('Fact'),
    routeIds: ids, entryIds: ids, evidenceIds: ids, generator: ref('ResourceGenerator') }, ['generator']),
  Section: object({ index: uint, id: { ...uint, maximum: 13 }, bytes: uint, payloadBytes: uint }),
  Artifact: object({ id, representation: fixed('canonical-native-wasm'), stage: en('final', 'prelink'),
    host: text, target: text, bytes: { ...uint, minimum: 8 }, sha256: hash, sections: array(ref('Section')),
    sectionCoverage: ref('Coverage'), evidenceIds: ids,
    ledger: object({ headerBytes: fixed(8), codeBodyBytes: uint, codeFramingBytes: uint,
      dataPayloadBytes: ref('Fact'), unattributedDataPayloadBytes: ref('Fact') }) }, ['ledger']),
  Body: object({ id, artifactId: id, index: uint, bytes: { ...uint, minimum: 1 } }),
  Implementation: object({ id, artifactId: id, canonicalId: nullable(text),
    origin: en('dedicated', 'authored-helper', 'consolidated-stage', 'dispatcher'),
    roles: array(en(...ENTRY_ROLES, 'helper')),
    consumerBasis: fixed('compiler-entry-association'), entryCoverage: ref('Coverage'),
    entryIds: ids, routeIds: ids, bodyIds: ids, evidenceIds: ids,
    chunks: { ...array(object({ chunk: uint, bodyId: nullable(id),
      reason: nullable(en('final-symbol-not-surviving')), entryIds: ids })), minItems: 1 },
    bodyCoverage: ref('Coverage') }),
  Root: object({ id, kind: en('route', 'event', 'startup', 'error', 'export', 'other'), subjectId: nullable(id), bodyIds: ids }),
  RootSet: object({ id, artifactId: id, universeComplete: bool, graph: en('static-direct-calls', 'unsupported'),
    roots: array(ref('Root')), evidenceIds: ids }),
  Measurement: object({ id, subjectId: id, artifactId: id, stage: en('final', 'prelink'),
    metric: en('handler-body', 'reachable', 'own', 'shared'), method: en('final-body-map-v1', 'static-direct-calls-v1', 'unavailable'),
    fact: ref('Fact'), mappedChunks: uint, expectedChunks: nullable(uint), bodyIds: ids, rootSetId: nullable(id), rootId: nullable(id) }),
  Observation: object({ id, code: text, severity: en('info', 'warning', 'error'), producer: ref('Producer'), subjectIds: ids, evidenceIds: ids,
    graphDiagnostic: ref('GraphDiagnostic') }, ['graphDiagnostic']),
  Evidence: object({ id, kind: en('build', 'source', 'declaration', 'measurement', 'test'), producer: ref('Producer'),
    method: text, artifactIds: ids, source: nullable(ref('Source')), subjectIds: ids,
    result: en('passed', 'failed', 'warning', 'observed', 'not-run'),
    scope: object({ corpus: nullable(text), cases: array(text), targets: array(text) }), recordedAt: nullable(text) })
};
const capsule = object({ kind: fixed('pulse.application-report'), reportVersion: fixed(1),
  producer: object({ pulseVersion: text, reporterVersion: text }), context: ref('Context'),
  provenance: object({ revision: nullable({ type: 'string', pattern: '^[a-f0-9]{40,64}$' }), dirty: nullable(bool),
    sourceFingerprint: nullable(hash), buildEvidenceId: id, toolchain: array(ref('Producer')), recipe: ref('Recipe') }),
  coverage: object(Object.fromEntries(['routes', 'entries', 'schemas', 'bindings', 'resources', 'references', 'implementations'].map(key => [key, ref('Coverage')])), ['references', 'implementations']),
  application: object({ name: text }), routes: array(ref('Route')), entries: array(ref('Entry')),
  declarations: array(ref('Declaration')), schemas: array(ref('Schema')), bindings: array(ref('Binding')),
  resources: array(ref('Resource')), artifacts: array(ref('Artifact')), bodies: array(ref('Body')),
  references: array(ref('Reference')),
  resourceProducers: array(ref('ResourceProducer')),
  implementations: array(ref('Implementation')),
  rootSets: array(ref('RootSet')), measurements: array(ref('Measurement')), observations: array(ref('Observation')),
  evidence: array(ref('Evidence')), evidenceHash: object({ algorithm: fixed('sha256'), value: hash }) }, ['references', 'resourceProducers', 'implementations']);
const completion = object({ kind: fixed('pulse.report-completion'), completionVersion: fixed(1), status: fixed('complete'),
  operation: en('compile', 'native-build'), manifestVersion: fixed('pulse.project-execution.v10'), context: ref('Context'),
  snapshot: object({ inputsSha256: hash, profileSha256: hash, recipeSha256: hash }),
  artifacts: array(object({ ...defs.File.properties, id, stage: en('final', 'prelink') })),
  sidecars: array({ oneOf: [
    object({ ...defs.File.properties, kind: fixed('inventory'), version: fixed(1), required: bool }),
    object({ ...defs.File.properties, kind: fixed('attribution'), version: en(1, 2), required: bool })
  ] }) });
const attribution = object({ kind: fixed('pulse.report-attribution'), attributionVersion: fixed(1),
  artifactId: id, artifactSha256: hash, stage: en('final', 'prelink'), importedFunctions: uint,
  functions: array(object({ index: uint, bytes: { ...uint, minimum: 1 } })),
  handlerBodies: array(object({ entryId: text, handlerId: text, chunks: array(uint) })),
  chunkMappings: array(object({ chunk: uint, functionIndex: nullable(uint), reason: nullable(en(...REASONS)) })),
  graph: object({ state: en('available', 'unavailable'), reason: nullable(en(...REASONS)),
    method: fixed('static-direct-calls-v1'), edges: array(object({ caller: uint, callee: uint, sites: { ...uint, minimum: 1 } })),
    diagnostic: ref('GraphDiagnostic') }, ['diagnostic']) });
const attributionV2 = object({ ...attribution.properties, attributionVersion: fixed(2),
  entries: array(object({ entryId: text, handlerId: nullable(text),
    bodies: array(object({ chunk: uint, relation: en(...BODY_KINDS) })),
    reason: nullable(en('entry-ownership-not-retained')) })),
  chunkMappings: array(object({ chunk: uint, kind: en(...BODY_KINDS), implementationId: nullable(text),
    functionIndex: nullable(uint), reason: nullable(en('final-symbol-not-surviving')) })) });
delete attributionV2.properties.handlerBodies;
attributionV2.required = attributionV2.required.filter(key => key !== 'handlerBodies');
function document(name, shape) {
  const used = {};
  function visit(node) {
    if (!node || typeof node !== 'object') return;
    if (node.$ref) {
      const key = node.$ref.slice('#/$defs/'.length);
      if (!used[key]) { used[key] = defs[key]; visit(defs[key]); }
    }
    Object.values(node).forEach(visit);
  }
  visit(shape);
  return freeze({ $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `urn:pulse:report:${name}:v1`, ...shape, $defs: used });
}
module.exports = { capsuleSchema: document('capsule', capsule), completionSchema: document('completion', completion),
  attributionSchema: document('attribution', { oneOf: [attribution, attributionV2] }),
  fileSchema: freeze(defs.File), REASONS: Object.freeze(REASONS), GRAPH_DIAGNOSTICS, RESOURCE_SCOPES: Object.freeze(RESOURCE_SCOPES) };
