'use strict';

// Canonical schema owner. The checked-in JSON schemas are generated by the
// contract test's explicit --write-fixtures mode, never edited independently.
const { LIMITS, freeze } = require('./data');
const str = { type: 'string', maxLength: LIMITS.stringBytes };
const text = { ...str, minLength: 1 };
const id = { type: 'string', pattern: '^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$' };
const hash = { type: 'string', pattern: '^[a-f0-9]{64}$' };
const uint = { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER };
const bool = { type: 'boolean' };
const en = (...values) => ({ enum: values });
const fixed = value => ({ const: value });
const ref = name => ({ $ref: '#/$defs/' + name });
const nullable = schema => ({ anyOf: [schema, { type: 'null' }] });
const array = items => ({ type: 'array', items, maxItems: LIMITS.records });
const object = (properties, optional = []) => ({ type: 'object', properties,
  required: Object.keys(properties).filter(key => !optional.includes(key)), additionalProperties: false });
const ids = array(id);
const REASONS = ['missing-evidence', 'unsupported-mapping', 'incomplete-mapping', 'incomplete-root-universe',
  'unsupported-call-graph', 'prelink-only', 'not-recorded', 'not-applicable', 'unsupported-schema-shape',
  'unsupported-schema-version', 'unsupported-constraint', 'upstream-partial'];
const defs = {
  Source: object({ file: text, line: { ...uint, minimum: 1 }, column: { ...uint, minimum: 1 },
    endLine: { ...uint, minimum: 1 }, endColumn: { ...uint, minimum: 1 } }, ['endLine', 'endColumn']),
  Coverage: object({ status: en('complete', 'partial', 'unavailable', 'not-applicable'),
    observed: uint, expected: nullable(uint), reason: nullable(en(...REASONS)) }),
  Fact: object({ state: en('available', 'unavailable', 'not-applicable'),
    basis: en('declared', 'resolved', 'measured', 'recorded'), coverage: en('exact', 'bounded', 'partial'),
    value: nullable(uint), reason: nullable(en(...REASONS)), evidenceIds: ids }),
  Producer: object({ name: text, version: text }),
  File: object({ file: text, bytes: uint, sha256: hash }),
  Context: object({ profile: text, host: text, target: fixed('native'), representation: fixed('canonical-native-wasm'), primaryArtifactId: id }),
  Recipe: object({ name: text, version: text, optimization: en('default', 'experimental-native-size', 'experimental-native-bounded-size', 'unavailable'), guestLinked: bool }),
  Route: object({ id, canonicalId: text, order: uint, method: text, path: str, handlerId: id,
    handlerName: nullable(str), entryId: id, source: nullable(ref('Source')), composition: ids,
    compositionCoverage: en('complete', 'bounded', 'unavailable'),
    schemaIds: ids, bindingIds: ids, declarationIds: ids, evidenceIds: ids }, ['compositionCoverage']),
  Entry: object({ id, canonicalId: text, kind: en('route', 'middleware', 'fallback', 'error', 'event', 'startup', 'export', 'other'),
    order: uint, handlerId: nullable(id), name: nullable(str), source: nullable(ref('Source')),
    schemaIds: ids, bindingIds: ids, declarationIds: ids, evidenceIds: ids,
    flow: object({ nextEntryId: nullable(id), childEntryId: nullable(id), parentContinueEntryId: nullable(id),
      routerPath: array(text), path: nullable(str), method: nullable(text), scoped: bool, conditional: bool }) }, ['flow']),
  Declaration: object({ id, kind: text, name: str, evidenceIds: ids }),
  Node: { oneOf: [
    object({ kind: en('string', 'boolean', 'i32', 'u32', 'f64', 'json-value', 'json-object') }),
    object({ kind: fixed('string-enum'), literalCount: { ...uint, minimum: 1 } }),
    object({ kind: fixed('scalar-record'), limits: ref('ScalarLimits') }),
    object({ kind: fixed('array'), element: ref('Node') }),
    object({ kind: fixed('nullable'), value: ref('Node') }),
    object({ kind: fixed('object'), fields: array(object({ name: text, required: bool, value: ref('Node') })), additionalProperties: bool })
  ] },
  ScalarLimits: object(Object.fromEntries(['maxKeys', 'maxKeyLength', 'maxStringLength', 'maxBytes', 'numberBytes'].map(key => [key, { ...uint, minimum: 1 }]))),
  JsonLimits: object(Object.fromEntries(['maxTextBytes', 'maxDepth', 'maxNodes', 'maxObjectMembers', 'maxArrayItems', 'maxKeyLength', 'maxStringLength', 'maxJsonBytes'].map(key => [key, { ...uint, minimum: 1 }]))),
  Descriptor: object({ representation: fixed('pulse.report-schema-shape.v1'), root: ref('Node'), jsonLimits: nullable(ref('JsonLimits')) }),
  Structure: object({ representation: fixed('pulse.report-schema-shape.v1'), state: en('available', 'unavailable'),
    reason: nullable(en(...REASONS)), descriptor: nullable(ref('Descriptor')), descriptorBytes: nullable(uint),
    keyCountsState: en('available', 'unavailable', 'not-applicable'), topLevelKeys: nullable(uint), requiredKeys: nullable(uint),
    properties: array(object({ name: text, type: text, required: nullable(bool) })) }),
  Schema: object({ id, schemaId: text, registryVersion: text, source: nullable(ref('Source')),
    structure: ref('Structure'), routeIds: ids, entryIds: ids, evidenceIds: ids }),
  Binding: object({ id, name: text, kind: text, declared: bool, referenced: bool,
    resolution: en('bound', 'unbound', 'unavailable'), routeIds: ids, entryIds: ids, evidenceIds: ids }),
  Resource: object({ id, name: text, kind: en('embedded-asset', 'schema-validator', 'helper', 'other'),
    mediaType: nullable(text), artifactId: nullable(id), inputBytes: ref('Fact'), retainedPayloadBytes: ref('Fact'),
    routeIds: ids, entryIds: ids, evidenceIds: ids }),
  Section: object({ index: uint, id: { ...uint, maximum: 13 }, bytes: uint, payloadBytes: uint }),
  Artifact: object({ id, representation: fixed('canonical-native-wasm'), stage: en('final', 'prelink'),
    host: text, target: text, bytes: { ...uint, minimum: 8 }, sha256: hash, sections: array(ref('Section')),
    sectionCoverage: ref('Coverage'), evidenceIds: ids,
    ledger: object({ headerBytes: fixed(8), codeBodyBytes: uint, codeFramingBytes: uint,
      dataPayloadBytes: ref('Fact'), unattributedDataPayloadBytes: ref('Fact') }) }, ['ledger']),
  Body: object({ id, artifactId: id, index: uint, bytes: { ...uint, minimum: 1 } }),
  Root: object({ id, kind: en('route', 'event', 'startup', 'error', 'export', 'other'), subjectId: nullable(id), bodyIds: ids }),
  RootSet: object({ id, artifactId: id, universeComplete: bool, graph: en('static-direct-calls', 'unsupported'),
    roots: array(ref('Root')), evidenceIds: ids }),
  Measurement: object({ id, subjectId: id, artifactId: id, stage: en('final', 'prelink'),
    metric: en('handler-body', 'reachable', 'own', 'shared'), method: en('final-body-map-v1', 'static-direct-calls-v1', 'unavailable'),
    fact: ref('Fact'), mappedChunks: uint, expectedChunks: nullable(uint), bodyIds: ids, rootSetId: nullable(id), rootId: nullable(id) }),
  Observation: object({ id, code: text, severity: en('info', 'warning', 'error'), producer: ref('Producer'), subjectIds: ids, evidenceIds: ids }),
  Evidence: object({ id, kind: en('build', 'source', 'declaration', 'measurement', 'test'), producer: ref('Producer'),
    method: text, artifactIds: ids, source: nullable(ref('Source')), subjectIds: ids,
    result: en('passed', 'failed', 'warning', 'observed', 'not-run'),
    scope: object({ corpus: nullable(text), cases: array(text), targets: array(text) }), recordedAt: nullable(text) })
};
const capsule = object({ kind: fixed('pulse.application-report'), reportVersion: fixed(1),
  producer: object({ pulseVersion: text, reporterVersion: text }), context: ref('Context'),
  provenance: object({ revision: nullable({ type: 'string', pattern: '^[a-f0-9]{40,64}$' }), dirty: nullable(bool),
    sourceFingerprint: nullable(hash), buildEvidenceId: id, toolchain: array(ref('Producer')), recipe: ref('Recipe') }),
  coverage: object(Object.fromEntries(['routes', 'entries', 'schemas', 'bindings', 'resources'].map(key => [key, ref('Coverage')]))),
  application: object({ name: text }), routes: array(ref('Route')), entries: array(ref('Entry')),
  declarations: array(ref('Declaration')), schemas: array(ref('Schema')), bindings: array(ref('Binding')),
  resources: array(ref('Resource')), artifacts: array(ref('Artifact')), bodies: array(ref('Body')),
  rootSets: array(ref('RootSet')), measurements: array(ref('Measurement')), observations: array(ref('Observation')),
  evidence: array(ref('Evidence')), evidenceHash: object({ algorithm: fixed('sha256'), value: hash }) });
const completion = object({ kind: fixed('pulse.report-completion'), completionVersion: fixed(1), status: fixed('complete'),
  operation: en('compile', 'native-build'), manifestVersion: fixed('pulse.project-execution.v10'), context: ref('Context'),
  snapshot: object({ inputsSha256: hash, profileSha256: hash, recipeSha256: hash }),
  artifacts: array(object({ ...defs.File.properties, id, stage: en('final', 'prelink') })),
  sidecars: array(object({ ...defs.File.properties, kind: en('inventory', 'attribution'), version: fixed(1), required: bool })) });
const attribution = object({ kind: fixed('pulse.report-attribution'), attributionVersion: fixed(1),
  artifactId: id, artifactSha256: hash, stage: en('final', 'prelink'), importedFunctions: uint,
  functions: array(object({ index: uint, bytes: { ...uint, minimum: 1 } })),
  handlerBodies: array(object({ entryId: text, handlerId: text, chunks: array(uint) })),
  chunkMappings: array(object({ chunk: uint, functionIndex: nullable(uint), reason: nullable(en(...REASONS)) })),
  graph: object({ state: en('available', 'unavailable'), reason: nullable(en(...REASONS)),
    method: fixed('static-direct-calls-v1'), edges: array(object({ caller: uint, callee: uint, sites: { ...uint, minimum: 1 } })) }) });
function document(name, shape) {
  const used = {};
  function visit(node) {
    if (!node || typeof node !== 'object') return;
    if (node.$ref) {
      const key = node.$ref.slice('#/$defs/'.length);
      if (!used[key]) { used[key] = defs[key]; visit(defs[key]); }
    }
    Object.values(node).forEach(visit);
  }
  visit(shape);
  return freeze({ $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: `urn:pulse:report:${name}:v1`, ...shape, $defs: used });
}
module.exports = { capsuleSchema: document('capsule', capsule), completionSchema: document('completion', completion),
  attributionSchema: document('attribution', attribution), fileSchema: freeze(defs.File), REASONS: Object.freeze(REASONS) };
