'use strict';

const DIAGNOSTIC_CODE_VERSION = 'pulsewasm.diagnostic-codes.v1';

const DIAGNOSTIC_CODES = Object.freeze({
  UNSUPPORTED_ROUTER_METHOD: 'PULSEWASM_UNSUPPORTED_ROUTER_METHOD',
  ARITY: 'PULSEWASM_ARITY',
  DYNAMIC_PATH: 'PULSEWASM_DYNAMIC_PATH',
  INVALID_PATH: 'PULSEWASM_INVALID_PATH',
  UNSUPPORTED_HANDLER: 'PULSEWASM_UNSUPPORTED_HANDLER',
  UNSUPPORTED_CHANNEL: 'PULSEWASM_UNSUPPORTED_CHANNEL',
  UNSUPPORTED_LIFECYCLE: 'PULSEWASM_UNSUPPORTED_LIFECYCLE',
  UNSUPPORTED_MOUNT_TARGET: 'PULSEWASM_UNSUPPORTED_MOUNT_TARGET',
  COMPUTED_METHOD: 'PULSEWASM_COMPUTED_METHOD',
  DYNAMIC_ROUTE_REGISTRATION: 'PULSEWASM_DYNAMIC_ROUTE_REGISTRATION',
  ROUTER_REASSIGNMENT: 'PULSEWASM_ROUTER_REASSIGNMENT',
  HANDLER_BINDING_UNKNOWN_HANDLER: 'PULSEWASM_HANDLER_BINDING_UNKNOWN_HANDLER',
  HANDLER_BINDING_INLINE_UNSUPPORTED: 'PULSEWASM_HANDLER_BINDING_INLINE_UNSUPPORTED',
  HANDLER_BINDING_NOT_EXPORTED: 'PULSEWASM_HANDLER_BINDING_NOT_EXPORTED',
  HANDLER_BINDING_EXPORT_NAME_MISSING: 'PULSEWASM_HANDLER_BINDING_EXPORT_NAME_MISSING',
  UNSUPPORTED_ROUTER_CONSTRUCTION: 'PULSEWASM_UNSUPPORTED_ROUTER_CONSTRUCTION',
  GUEST_UNIT_INVALID: 'PULSE_GUEST_UNIT_INVALID',
  GUEST_UNIT_HASH_MISMATCH: 'PULSE_GUEST_UNIT_HASH_MISMATCH',
  GUEST_UNIT_OWNER_MISMATCH: 'PULSE_GUEST_UNIT_OWNER_MISMATCH',
  GUEST_UNIT_ABI_MISMATCH: 'PULSE_GUEST_UNIT_ABI_MISMATCH',
  GUEST_UNIT_IMPORT_MISMATCH: 'PULSE_GUEST_UNIT_IMPORT_MISMATCH',
  GUEST_UNIT_EXPORT_MISMATCH: 'PULSE_GUEST_UNIT_EXPORT_MISMATCH',
  GUEST_UNIT_MEMORY_MISMATCH: 'PULSE_GUEST_UNIT_MEMORY_MISMATCH',
  GUEST_UNIT_START_MISMATCH: 'PULSE_GUEST_UNIT_START_MISMATCH',
  GUEST_UNIT_FEATURE_MISMATCH: 'PULSE_GUEST_UNIT_FEATURE_MISMATCH',
  GUEST_UNIT_MATERIALIZATION_FAILED: 'PULSE_GUEST_UNIT_MATERIALIZATION_FAILED',
  GUEST_UNIT_CARDINALITY_UNSUPPORTED: 'PULSE_GUEST_UNIT_CARDINALITY_UNSUPPORTED',
  GUEST_TARGET_POLICY_REQUIRED: 'PULSE_GUEST_TARGET_POLICY_REQUIRED',
  GUEST_LINK_FAILED: 'PULSE_GUEST_LINK_FAILED',
  GUEST_OPTIMIZATION_FAILED: 'PULSE_GUEST_OPTIMIZATION_FAILED',
  GUEST_FINAL_AUDIT_FAILED: 'PULSE_GUEST_FINAL_AUDIT_FAILED'
});

module.exports = {
  DIAGNOSTIC_CODE_VERSION,
  DIAGNOSTIC_CODES
};
