# Generated from @pulse-compute/cli/src/command-spec.js.
# Install for the current shell with: pulse completion fish | source
complete -c pulse -f
complete -c pulse -n '__fish_use_subcommand' -a 'init' -d 'Create a conventional .pulse workspace with an async Pulse application and dedicated test harness.'
complete -c pulse -n '__fish_use_subcommand' -a 'doctor' -d 'Audit project shape, compilation, schemas, provider bindings, output safety, and required tools.'
complete -c pulse -n '__fish_use_subcommand' -a 'inspect' -d 'Report canonical compiler, schema, effect, continuation, capability, provider, and build-mode details.'
complete -c pulse -n '__fish_use_subcommand' -a 'test' -d 'Run configured cases through the selected provider local-conformance runtime.'
complete -c pulse -n '__fish_use_subcommand' -a 'dev' -d 'Start the foreground local server with the selected provider conformance runtime.'
complete -c pulse -n '__fish_use_subcommand' -a 'compile' -d 'Compile the canonical project into provider-neutral Pulse-owned WebAssembly.'
complete -c pulse -n '__fish_use_subcommand' -a 'build' -d 'Compile the canonical project and realize the deployment provider selected by the active project profile.'
complete -c pulse -n '__fish_use_subcommand' -a 'completion' -d 'Print a generated shell completion script'
complete -c pulse -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c pulse -n '__fish_use_subcommand' -a 'help version'
complete -c pulse -n '__fish_use_subcommand' -l help -d 'Print public help'
complete -c pulse -n '__fish_use_subcommand' -s h -d 'Print public help'
complete -c pulse -n '__fish_use_subcommand' -l version -d 'Print the installed CLI version'
complete -c pulse -n '__fish_use_subcommand' -s v -d 'Print the installed CLI version'
complete -c pulse -n '__fish_seen_subcommand_from init' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from init' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from init' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from init' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from init' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from init' -l force -d 'Allow generated files to replace entries in a non-empty target directory.'
complete -c pulse -n '__fish_seen_subcommand_from init' -l name -r -d 'Set the generated npm package name.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -l strict -d 'Treat doctor warnings as failed checks.'
complete -c pulse -n '__fish_seen_subcommand_from doctor' -l profile -r -d 'Select a project profile. Precedence: --profile, PULSE_PROFILE, pulse.defaultProfile.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -l profile -r -d 'Select a project profile. Precedence: --profile, PULSE_PROFILE, pulse.defaultProfile.'
complete -c pulse -n '__fish_seen_subcommand_from inspect' -l artifact -r -d 'Inspect an existing JSON build or compiler artifact instead of a project.'
complete -c pulse -n '__fish_seen_subcommand_from test' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from test' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from test' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from test' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from test' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from test' -l profile -r -d 'Select a project profile. Precedence: --profile, PULSE_PROFILE, pulse.defaultProfile.'
complete -c pulse -n '__fish_seen_subcommand_from test' -l case -r -d 'Run one named project test case.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l once -d 'Close the development server after the first completed request.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l watch -d 'Enable or disable entry and schema dependency watching. Watching is enabled by default.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l no-watch -d 'Enable or disable entry and schema dependency watching. Watching is enabled by default.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l profile -r -d 'Select a project profile. Precedence: --profile, PULSE_PROFILE, pulse.defaultProfile.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l host -r -d 'Override the development listen host.'
complete -c pulse -n '__fish_seen_subcommand_from dev' -l port -r -d 'Override the development listen port. Use 0 to request an ephemeral port.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l clean -d 'Remove or preserve the selected output directory before writing artifacts. Cleaning is enabled by default.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l no-clean -d 'Remove or preserve the selected output directory before writing artifacts. Cleaning is enabled by default.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l emit-wat -d 'Also emit diagnostic WebAssembly text (WAT). Native builds omit it by default; large text emission can exhaust compiler string capacity.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l experimental-native-bounded-size -d 'Experimentally optimize Native Wasm with shrink level 2 without convergence. JavaScript build targets reject this flag.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l experimental-native-size -d 'Experimentally optimize Native Wasm for size. JavaScript build targets reject this flag.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l profile -r -d 'Select a project profile. Precedence: --profile, PULSE_PROFILE, pulse.defaultProfile.'
complete -c pulse -n '__fish_seen_subcommand_from compile' -l out -r -d 'Override the project-relative artifact output directory.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l help -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from build' -s h -d 'Print public CLI help and exit.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l json -d 'Emit machine-readable JSON. pulse dev emits one JSON event per line.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l dry-run -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l plan -d 'Resolve and report the command plan without executing it.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l clean -d 'Remove or preserve the selected output directory before writing artifacts. Cleaning is enabled by default.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l no-clean -d 'Remove or preserve the selected output directory before writing artifacts. Cleaning is enabled by default.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l emit-wat -d 'Also emit diagnostic WebAssembly text (WAT). Native builds omit it by default; large text emission can exhaust compiler string capacity.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l experimental-native-bounded-size -d 'Experimentally optimize Native Wasm with shrink level 2 without convergence. JavaScript build targets reject this flag.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l experimental-native-size -d 'Experimentally optimize Native Wasm for size. JavaScript build targets reject this flag.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l profile -r -d 'Select a project profile. Precedence: --profile, PULSE_PROFILE, pulse.defaultProfile.'
complete -c pulse -n '__fish_seen_subcommand_from build' -l out -r -d 'Override the project-relative artifact output directory.'
