'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const crypto = require('node:crypto');
const { PACKAGE_VERSION, normalizeArtifact, normalizeDiagnostic } = require('../diagnostics.js');

const WRAPPER_INTEGRATION_VERSION = 'pulsewasm.wrapper-integration.v1';
const PULSE_BUILD_OUTPUT_VERSION = 'pulsewasm.pulse-build-output.v1';
const PULSE_DEV_RUNTIME_VERSION = 'pulsewasm.pulse-dev-runtime.v1';
const PHASE = '13A';

function sha256Text(text) { return crypto.createHash('sha256').update(String(text || ''), 'utf8').digest('hex'); }
function makeFile(file, text) { return { file, text, bytes: Buffer.byteLength(text, 'utf8'), sha256: sha256Text(text) }; }
function diagnostic(code, message, hint, details) {
  return normalizeDiagnostic({ phase: 'pulse-wrapper', severity: 'error', code, message, hint, details, loc: { file: '<pulse-wrapper>' } });
}
function readOutputBuffer(output) { return output && output.file && fs.existsSync(output.file) ? fs.readFileSync(output.file) : undefined; }
function writeTempFile(root, file, textOrBuffer) {
  const abs = path.join(root, file);
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, textOrBuffer);
  return abs;
}
function jsonText(value) { return `${JSON.stringify(value, null, 2)}\n`; }
function normalizeHeaders(headers) { return (headers || []).map((pair) => [String(pair[0]), String(pair[1])]); }

function buildWrapperSource() {
  return `/* Generated by PulseWasm Phase 13A.\n * High-level Pulse wrapper integration over the compiled-Wasm local runtime.\n */\n'use strict';\nconst fs = require('node:fs');\nconst path = require('node:path');\n\nfunction defineConfig(configOrFactory) { return configOrFactory; }\nfunction readJson(file) { return JSON.parse(fs.readFileSync(file, 'utf8')); }\nfunction defaultArtifactDir() { return path.resolve(__dirname, '../..'); }\nfunction artifactDirFrom(options) { return path.resolve(options && options.artifactDir ? options.artifactDir : defaultArtifactDir()); }\nfunction artifactPath(artifactDir, file) { return path.join(artifactDir, file); }\nfunction safeReadJson(artifactDir, file) { const target = artifactPath(artifactDir, file); return fs.existsSync(target) ? readJson(target) : undefined; }\n\nfunction createPulseBuildOutput(options = {}) {\n  const artifactDir = artifactDirFrom(options);\n  const resolvedConfig = safeReadJson(artifactDir, 'resolved-config.json');\n  const deploymentPosture = safeReadJson(artifactDir, 'deployment-posture.json');\n  const buildManifest = safeReadJson(artifactDir, 'build-manifest.json');\n  const artifacts = {\n    resolvedConfig: 'resolved-config.json',\n    deploymentPosture: 'deployment-posture.json',\n    compiledWasmRuntime: 'compiled-wasm-runtime.json',\n    compiledWasmHostRuntime: 'compiled-wasm-host-runtime.json',\n    compiledWasmNodeAdapter: 'compiled-wasm-node-adapter.json',\n    compiledWasmRuntimeSmoke: 'compiled-wasm-runtime-smoke.json',\n    wasm: 'generated/compiled-wasm-runtime/pulsewasm-compiled-runtime.wasm',\n    hostRuntime: 'generated/host/compiled-wasm-host-runtime.cjs',\n    nodeAdapter: 'generated/node/compiled-wasm-node-adapter.cjs'\n  };\n  return {\n    version: 'pulsewasm.pulse-build-output.runtime.v1',\n    artifactDir,\n    profile: resolvedConfig && resolvedConfig.profile,\n    runtime: resolvedConfig && resolvedConfig.runtime,\n    engine: deploymentPosture && deploymentPosture.engine,\n    handlerExecutionMode: resolvedConfig && resolvedConfig.runtime && resolvedConfig.runtime.handlerExecutionMode,\n    deploymentPosture,\n    buildManifest,\n    artifacts\n  };\n}\n\nfunction createPulseDevRuntime(options = {}) {\n  const artifactDir = artifactDirFrom(options);\n  const buildOutput = createPulseBuildOutput({ artifactDir });\n  const posture = options.deploymentPosture || buildOutput.deploymentPosture || { engine: 'wasm' };\n  if ((posture.engine || 'wasm') === 'js' && !options.allowJsEngine) {\n    const err = new Error('Pulse dev runtime refuses JS engine posture for the Wasm wrapper path.');\n    err.code = 'PULSEWASM_WRAPPER_ENGINE_MISMATCH';\n    throw err;\n  }\n  const hostRuntimePath = options.hostRuntimePath || artifactPath(artifactDir, buildOutput.artifacts.hostRuntime);\n  const nodeAdapterPath = options.nodeAdapterPath || artifactPath(artifactDir, buildOutput.artifacts.nodeAdapter);\n  const wasmPath = options.wasmPath || artifactPath(artifactDir, buildOutput.artifacts.wasm);\n  if (!fs.existsSync(hostRuntimePath)) { const err = new Error('Missing compiled-wasm host runtime artifact.'); err.code = 'PULSEWASM_WRAPPER_HOST_RUNTIME_MISSING'; throw err; }\n  if (!fs.existsSync(nodeAdapterPath)) { const err = new Error('Missing compiled-wasm Node adapter artifact.'); err.code = 'PULSEWASM_WRAPPER_NODE_ADAPTER_MISSING'; throw err; }\n  if (!fs.existsSync(wasmPath)) { const err = new Error('Missing compiled-wasm runtime .wasm artifact.'); err.code = 'PULSEWASM_WRAPPER_WASM_MISSING'; throw err; }\n  const { createPulseWasmCompiledHostRuntime } = require(hostRuntimePath);\n  const { createPulseWasmCompiledNodeAdapter, createNodeHandler, createNodeServer } = require(nodeAdapterPath);\n  const runtime = createPulseWasmCompiledHostRuntime({\n    wasmPath,\n    deploymentPosture: posture,\n    hostResponses: options.hostResponses\n  });\n  const nodeAdapter = createPulseWasmCompiledNodeAdapter({ runtime });\n  return {\n    version: 'pulsewasm.pulse-dev-runtime.runtime.v1',\n    engine: posture.engine || 'wasm',\n    handlerExecutionMode: 'compiled-wasm',\n    buildOutput,\n    runtime,\n    nodeAdapter,\n    executeRequest(input) { return runtime.executeRequest(input); },\n    executeConnect(input) { return runtime.executeConnect(input); },\n    executeDisconnect(input) { return runtime.executeDisconnect(input); },\n    createNodeHandler(options = {}) { return createNodeHandler(runtime, options); },\n    createNodeServer(options = {}) { return createNodeServer(runtime, options); },\n    close() { if (runtime.close) return runtime.close(); }\n  };\n}\n\nfunction createPulseNodeHandler(options = {}) {\n  return createPulseDevRuntime(options).createNodeHandler(options);\n}\n\nmodule.exports = {\n  defineConfig,\n  createPulseBuildOutput,\n  createPulseDevRuntime,\n  createPulseNodeHandler\n};\n`;
}

function buildMarkdown(artifact) {
  const lines = [];
  lines.push('# PulseWasm Phase 13A — High-Level Wrapper Integration');
  lines.push('');
  lines.push('The wrapper is a thin paved path over the existing compiled-Wasm local runtime. It consumes artifacts; it does not redefine extraction, handler lowering, sidecar semantics, effects, or platform behavior.');
  lines.push('');
  lines.push('## Locked config shape');
  lines.push('');
  lines.push('- Root config defines source topology only: `entry`, `rootRouter`, and `profiles`.');
  lines.push('- `PULSE_PROFILE` / CLI profile selects the active profile.');
  lines.push('- Profile `runtime` defines engine, handler execution mode, timeouts, payload, and capabilities.');
  lines.push('- Profiles may not change route topology.');
  lines.push('');
  lines.push('## Wrapper exports');
  for (const name of artifact.wrapper.exports) lines.push(`- \`${name}\``);
  lines.push('');
  lines.push('## Smoke');
  lines.push(`- Checks: \`${artifact.summary.smokeChecks}\``);
  lines.push(`- Failed checks: \`${artifact.summary.failedSmokeChecks}\``);
  return `${lines.join('\n')}\n`;
}

function runWrapperSmoke({ wrapperSource, compiledWasmRuntime, resolvedConfig, deploymentPosture }) {
  const checks = [];
  const failedChecks = [];
  function check(name, actual, expected) {
    const passed = actual === expected;
    const record = { name, actual, expected, passed };
    checks.push(record);
    if (!passed) failedChecks.push(record);
  }
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pulsewasm-13a-wrapper-'));
  try {
    writeTempFile(tmp, 'generated/pulse/pulse-wrapper.cjs', wrapperSource);
    for (const file of compiledWasmRuntime.files || []) writeTempFile(tmp, file.file, file.text);
    for (const output of compiledWasmRuntime.outputFiles || []) {
      const buffer = readOutputBuffer(output);
      if (buffer) writeTempFile(tmp, output.file.replace(/^.*?generated\//, 'generated/'), buffer);
    }
    writeTempFile(tmp, 'resolved-config.json', jsonText(resolvedConfig));
    writeTempFile(tmp, 'deployment-posture.json', jsonText(deploymentPosture));
    writeTempFile(tmp, 'build-manifest.json', jsonText({ version: 'pulsewasm.wrapper-smoke-manifest.v1' }));
    const wrapper = require(path.join(tmp, 'generated/pulse/pulse-wrapper.cjs'));
    check('defineConfig_function', typeof wrapper.defineConfig, 'function');
    check('createPulseBuildOutput_function', typeof wrapper.createPulseBuildOutput, 'function');
    check('createPulseDevRuntime_function', typeof wrapper.createPulseDevRuntime, 'function');
    const output = wrapper.createPulseBuildOutput({ artifactDir: tmp });
    check('build_output_profile', output.profile, resolvedConfig.profile);
    check('build_output_engine', output.engine, 'wasm');
    check('build_output_handler_mode', output.handlerExecutionMode, 'compiled-wasm');
    const dev = wrapper.createPulseDevRuntime({ artifactDir: tmp });
    check('dev_runtime_engine', dev.engine, 'wasm');
    check('dev_runtime_handler_mode', dev.handlerExecutionMode, 'compiled-wasm');
    const schemaOk = dev.executeRequest({ method: 'POST', path: '/users', bodyText: '{"name":"Ada","age":37,"active":true}' });
    check('schema_success_status', schemaOk.status, 201);
    check('schema_success_kind', schemaOk.kind, 'json');
    const schemaBad = dev.executeRequest({ method: 'POST', path: '/users', bodyText: '{"name":"Ada","age":"bad","active":true}' });
    check('schema_error_status', schemaBad.status, 400);
    const extension = dev.executeRequest({ method: 'GET', path: '/extension' });
    check('extension_status', extension.status, 220);
    const stream = dev.nodeAdapter.executeRequest({ method: 'GET', path: '/stream' });
    check('stream_kind', stream.kind, 'stream');
    check('stream_response_ref', stream.responseRef, 77);
    check('no_js_handlers_required', dev.runtime.handlerExecutionMode, 'compiled-wasm');
    try {
      wrapper.createPulseDevRuntime({ artifactDir: tmp, deploymentPosture: { engine: 'js' } });
      check('js_posture_rejected', false, true);
    } catch (error) {
      check('js_posture_rejected', error.code === 'PULSEWASM_WRAPPER_ENGINE_MISMATCH', true);
    }
  } catch (error) {
    failedChecks.push({ name: 'wrapper_smoke_exception', actual: error && error.message ? error.message : String(error), expected: 'no exception', passed: false });
  }
  return { checks, failedChecks, tmp };
}

function buildPulseWrapperIntegration(inputs = {}, options = {}) {
  const generatedBy = options.generatedBy || PACKAGE_VERSION;
  const resolvedConfig = options.resolvedConfig || inputs.resolvedConfig || {};
  const compiledWasmRuntime = inputs.compiledWasmRuntime;
  const deploymentPosture = inputs.deploymentPosture?.artifact || inputs.deploymentPosture || { engine: 'wasm', wasmOptimized: true };
  const diagnostics = [];
  if (!compiledWasmRuntime || !compiledWasmRuntime.artifact) {
    diagnostics.push(diagnostic('PULSEWASM_WRAPPER_COMPILED_RUNTIME_REQUIRED', 'Phase 13A requires compiled-wasm-runtime.json.', 'Enable --emit-compiled-wasm-runtime before --emit-pulse-wrapper.'));
  }
  if ((resolvedConfig.version || '') !== 'pulsewasm.resolved-config.v2') {
    diagnostics.push(diagnostic('PULSEWASM_WRAPPER_CONFIG_V2_REQUIRED', 'Phase 13A requires resolved-config.v2.', 'Use config with root entry/rootRouter/profiles and runtime settings under the selected profile.'));
  }
  const wrapperSource = buildWrapperSource();
  let smoke = { checks: [], failedChecks: [] };
  if (diagnostics.length === 0) {
    smoke = runWrapperSmoke({ wrapperSource, compiledWasmRuntime, resolvedConfig, deploymentPosture });
    if (smoke.failedChecks.length > 0) {
      diagnostics.push(diagnostic('PULSEWASM_WRAPPER_SMOKE_FAILED', 'Pulse wrapper integration smoke checks failed.', 'Inspect wrapper-integration.json smoke checks.', { failedChecks: smoke.failedChecks }));
    }
  }

  const buildOutput = normalizeArtifact({
    version: PULSE_BUILD_OUTPUT_VERSION,
    generatedBy,
    phase: PHASE,
    profile: resolvedConfig.profile,
    entry: resolvedConfig.entry,
    rootRouter: resolvedConfig.rootRouter,
    runtime: resolvedConfig.runtime,
    engine: deploymentPosture.engine || 'wasm',
    handlerExecutionMode: resolvedConfig.runtime?.handlerExecutionMode || 'compiled-wasm',
    artifacts: {
      resolvedConfig: 'resolved-config.json',
      deploymentPosture: 'deployment-posture.json',
      compiledWasmRuntime: 'compiled-wasm-runtime.json',
      wasm: 'generated/compiled-wasm-runtime/pulsewasm-compiled-runtime.wasm',
      wrapper: 'generated/pulse/pulse-wrapper.cjs'
    }
  });
  const devRuntime = normalizeArtifact({
    version: PULSE_DEV_RUNTIME_VERSION,
    generatedBy,
    phase: PHASE,
    engine: deploymentPosture.engine || 'wasm',
    handlerExecutionMode: 'compiled-wasm',
    nodeAdapter: true,
    compiledWasmRuntime: true,
    jsUserHandlerImports: false,
    noAutomaticFallback: true,
    summary: {
      requestPathProven: diagnostics.length === 0,
      schemaRouteProven: smoke.checks.some((check) => check.name === 'schema_success_status' && check.passed),
      extensionRouteProven: smoke.checks.some((check) => check.name === 'extension_status' && check.passed),
      streamRouteProven: smoke.checks.some((check) => check.name === 'stream_kind' && check.passed)
    }
  });
  const artifact = normalizeArtifact({
    version: WRAPPER_INTEGRATION_VERSION,
    generatedBy,
    phase: PHASE,
    status: diagnostics.length === 0 ? 'ok' : 'error',
    policy: {
      wrapperIsThin: true,
      consumesArtifacts: true,
      redefinesSemantics: false,
      platformAdapter: false,
      automaticJsFallback: false,
      configContract: 'root topology + profile runtime settings'
    },
    config: {
      version: resolvedConfig.version,
      entry: resolvedConfig.entry,
      rootRouter: resolvedConfig.rootRouter,
      profile: resolvedConfig.profile,
      runtime: resolvedConfig.runtime,
      selectedProfileFieldPresent: Object.prototype.hasOwnProperty.call(resolvedConfig, 'selectedProfile'),
      profileSourceFieldPresent: Object.prototype.hasOwnProperty.call(resolvedConfig, 'profileSource')
    },
    wrapper: {
      file: 'generated/pulse/pulse-wrapper.cjs',
      exports: ['defineConfig', 'createPulseBuildOutput', 'createPulseDevRuntime', 'createPulseNodeHandler']
    },
    smoke,
    summary: {
      smokeChecks: smoke.checks.length,
      failedSmokeChecks: smoke.failedChecks.length,
      profile: resolvedConfig.profile,
      engine: deploymentPosture.engine || 'wasm',
      handlerExecutionMode: resolvedConfig.runtime?.handlerExecutionMode || 'compiled-wasm',
      compiledWasmRuntime: Boolean(compiledWasmRuntime?.artifact),
      nodeAdapterPath: true,
      noJsHandlerImports: true,
      automaticFallback: false
    },
    diagnostics
  });
  return {
    artifact,
    buildOutput,
    devRuntime,
    files: [
      makeFile('generated/pulse/pulse-wrapper.cjs', wrapperSource),
      makeFile('generated/host/pulse-wrapper-integration.md', buildMarkdown(artifact))
    ],
    diagnostics
  };
}

module.exports = { buildPulseWrapperIntegration };
